{363}{476}SUPERMARCHÉ Mt FOODMORE|COMTÉ DE LOUDOUN, VIRGINIE
{2033}{2094}INFORMATEUR HEBDOMADAIRE
{2516}{2578}Il est temps d'entrer en action.
{2608}{2652}FBI ! Couchez-vous !
{2716}{2776}Arrêtez le tapis roulant.
{2919}{3008}- Le Pousseur, je présume.|- Vous êtes Frank Burst.
{3010}{3083}Honnêtement,|votre nom est très chouette.
{3085}{3150}Collins, lisez-lui ses droits.
{3152}{3213}Vous avez le droit de garder le silence.
{3215}{3283}Tout ce que vous direz|pourra être utilisé contre vous.
{3285}{3357}- Vous croyez me retenir ?|- Enchaînez-le !
{3359}{3460}Je veux une voiture cellulaire !|Je le surveillerai.
{3799}{3866}Connaître votre nom m'aiderait bien.
{3868}{3918}Le Pousseur suffit amplement.
{3963}{4099}Shérif adjoint, le bleu de votre uniforme|est extrêmement reposant.
{4101}{4213}Je suis attentif à ces choses-là.|Il est bleu ciel.
{4329}{4413}Très apaisant. Très... serein.
{4438}{4542}Je crois que ce ton de bleu s'appelle céruléen.
{4560}{4652}- Bleu céruléen.|- On a compris. C'est un beau bleu.
{4654}{4706}Bleu céruléen.
{4744}{4805}Céruléen, cela me fait penser à la brise.
{4826}{4915}- Une brise légère.|- Hé, mettez-la en veilleuse.
{4917}{4996}Céruléen est une brise légère.
{5013}{5095}Céruléen. Brise légère.
{5208}{5254}Arrêtez-vous !
{5518}{5579}LE GOUVERNEMENT NOUS MENT
{5932}{5974}LA VÉRITÉ EST AILLEURS
{6035}{6101}Le choc m'a fait perdre conscience.
{6103}{6161}L'adjoint Kerber était blessé à mort.
{6163}{6310}Avant de mourir, il a réussi à sortir|de la voiture, à prendre ses clés.
{6312}{6409}Il a rendu l'âme en libérant mon prisonnier,
{6411}{6527}qui a réussi à s'enfuir à pied|malgré ses blessures.
{6529}{6574}Il se fait appeler le Pousseur.
{6576}{6648}- Ses antécédents ?|- Il m'a appelé il y a un mois.
{6650}{6750}Il a avoué une série de meurtres|survenus depuis plus de deux ans.
{6757}{6866}- Pour se livrer ?|- Non. C'était un jeu, il se vantait.
{6868}{6956}Seulement, ces meurtres|ne sont pas reconnus comme tels.
{6964}{7038}Ils ont été classés comme des suicides.
{7040}{7111}- Donc vous pensez qu'il s'agit d'un fou.|- Non.
{7113}{7165}Il connaît trop bien ces affaires.
{7167}{7245}Des détails qu'il n'y avait|que dans nos dossiers.
{7247}{7305}Y a-t-il un rapport entre lui et l'adjoint ?
{7307}{7415}Pas que je sache.|Kerber était un bon policier.
{7417}{7490}Pourquoi l'a-t-il libéré ?
{7551}{7615}Le Pousseur parlait de bleu céruléen,
{7617}{7726}il n'arrêtait pas de dire|que cela lui rappelait la brise.
{7742}{7819}"Le bleu céruléen est une brise légère."
{7821}{7871}Encore, et encore.
{7873}{7988}Puis Kerber a démarré devant le camion et... bang.
{8001}{8132}Vous pensez que le Pousseur l'a induit|à agir de cette façon ?
{8134}{8183}Induit ? Comment ?
{8185}{8235}Oui, comment ?
{8272}{8342}Je n'en sais pas plus que vous.
{8401}{8466}Le Pousseur aime laisser des indices.
{8850}{8951}- Ronin.|- Ronin. Un samouraï sans maître.
{9006}{9076}- Tu n'as jamais vu Yojimbo ?|- Qu'est-ce que ça veut dire ?
{9078}{9163}Je sais ce qu'il cache|derrière la cuvette des WC.
{9165}{9202}RONIN AMÉRICAIN
{9296}{9361}Tenez, voici le numéro dix.
{9455}{9506}Je n'ai pas pu m'empêcher de le voir.
{9508}{9600}Ce week-end, un type m'a frappée pour me voler mon sac.
{9602}{9661}- Il a été arrêté ?|- Bien sûr que non.
{9677}{9726}Sans vouloir vous vexer.
{9728}{9778}Excusez-moi.
{9872}{9993}- Que cherchons-nous au juste ?|- Un samouraï doit passer des annonces.
{9995}{10074}Des annonces pour quoi ? Enfin...
{10076}{10205}Comment le Pousseur a-t-il persuadé|un shérif adjoint de le libérer ?
{10232}{10312}- Tu as bien une idée.|- Le pouvoir de suggestion.
{10314}{10400}C'est ce sur quoi l'hypnose est fondée,|comme la publicité.
{10402}{10457}Ile met des idées dans la tête.
{10459}{10575}Pousser à acheter est une chose,|provoquer un accident en est une autre.
{10577}{10686}Le principe est le même,|sauf qu'il est plus puissant.
{10688}{10805}C'est le Pousseur. Parce qu'il pousse les gens à agir à sa guise ?
{10807}{10934}Pourquoi provoquerait-il un accident|s'il est dans la voiture ?
{10936}{11028}Peut-être ne veut-il|en aucun cas aller en prison.
{11094}{11152}Regarde ça.
{11186}{11249}"Je résous les problèmes. OSU."
{11251}{11310}OSU. Ohio State University ?
{11346}{11511}Non, c'est le préfixe de la Virginie.|Tous les numéros publient ça depuis 1994.
{11513}{11578}Date à laquelle les crimes ont commencé.
{11734}{11788}DICTIONNAIRE JAPONAIS-ANGLAIS
{11840}{11890}OSU.
{11910}{11962}OS...
{11974}{12024}U. Mince !
{12049}{12121}Osu. C'est un mot japonais : "pousser".
{12123}{12210}Surveillons ces numéros de téléphone.
{12229}{12319}PARKING DE BANLIEUE|FALLS CHURCH, VIRGINIE
{12684}{12779}- Hé. Tu as bavé sur moi.|- Excuse-moi.
{12810}{12898}- Quelle heure est-il ?|- Il est... trois heures moins vingt.
{12923}{12993}- Rien, je suppose.|- Aux autres téléphones non plus.
{12995}{13085}Burst pense que c'est une fausse piste.
{13412}{13428}Allô ?
{13430}{13515}Allez-vous passer la nuit ici ?
{13517}{13606}Ne cherchez pas à me repérer,|je suis loin.
{13608}{13685}- Ils ont la trace.|- Je vous regardais il y a une heure.
{13687}{13781}Vous et votre jolie collègue|semblez très unis.
{13783}{13855}- Travaillez-vous bien ensemble ?|- Qui est-ce ?
{13857}{13960}- Votre nom ?|- Désolé. Ce n'est pas aussi simple.
{13962}{14128}Suivez mes miettes de pain. Montrez|ce que vous valez. Vous vous en tirez bien.
{14130}{14244}Pourquoi vous montrerais-je ma valeur ?|Est-ce un jeu pour vous ?
{14266}{14326}Voulez-vous être trouvé ?
{14385}{14479}- Où est ma prochaine miette de pain ?|- Devant vous.
{14481}{14556}Laissez vos doigts courir, agent.
{14607}{14657}- On ne l'a pas localisé.|- Bon.
{14659}{14767}Trace incomplète.|Il devait avoir un brouilleur numérique.
{14796}{14884}- "Laissez vos doigts courir."|- L'annuaire.
{14893}{14996}S'il s'était servi de ce téléphone ?|On peut rappeler le dernier numéro ?
{14998}{15048}Une seconde.
{15074}{15142}- Murphy.|- C'est encore moi.
{15144}{15252}Nous voulons le dernier numéro appelé d'ici. Passez-le-nous.
{15254}{15304}- Bien.|- Bon.
{15468}{15576}Bonjour, ici le cercle de golf|Au Club des Fans du Club.
{15578}{15694}Nous sommes ouverts de 7 h à minuit|du lundi au samedi,
{15696}{15748}et de 7 h à 22 h le dimanche.
{15750}{15830}- Un tueur golfeur.|- La puce à l'oreille ?
{15832}{15891}Viens, agente.
{16026}{16092}Oui ! Un tir puissant.
{16094}{16241}Joli. Bien, messieurs.|Je me sers d'une balle non autorisée.
{16243}{16346}Ile contient un noyau d'uranium,|ou de je ne sais quoi.
{16348}{16420}Ile s'envole comme un Spoutnik.
{16464}{16504}Oui !
{16875}{16926}Ce n'est pas trop tôt.
{16928}{17000}Konnichiwa, messieurs. Je n'étais pas là.
{17268}{17332}- Police ! Couchez-vous !|- Bon.
{17334}{17384}Bon. Bon, du calme.
{17428}{17478}Du calme.
{17537}{17605}Montrez-moi votre visage.
{17607}{17673}Doucement. Allez.
{17741}{17791}Bien.
{17850}{17906}Bien.
{17908}{17950}Bonjour, Collins.
{17976}{18041}Écoutez.
{18043}{18113}Faites quelque chose|pour moi.
{18141}{18181}SSNC
{18205}{18270}Pouvez-vous faire quelque chose pour moi ?
{18352}{18401}Mulder.
{18489}{18539}Collins ?
{18566}{18625}Mais qu'est-ce... ?
{18651}{18701}Qu'est-ce que vous faites ?
{18728}{18779}Collins, lâchez-le.
{18799}{18857}Arrêtez-moi !
{18877}{18927}Collins !
{18994}{19049}Posez ça.
{19262}{19318}Allumez, allumez.
{19320}{19429}Ici Burst. Envoyez des infirmiers.|Collins est brûlé.
{19431}{19527}Oui, très grave.|Je ne sais pas ce qui s'est passé. Venez !
{19559}{19623}Envoyez quelqu'un. Immédiatement !
{19677}{19725}Ça ira, Collins.
{19921}{20006}- FBI !|- Allumez. Allumez.
{20020}{20070}Allumez.
{20131}{20185}Cinq dollars que je serai relâché.
{20304}{20380}Levez-vous, déclinez vos nom et adresse.
{20394}{20449}SALLE D'AUDIENCE A
{20451}{20506}Robert Patrick Modell,
{20508}{20657}3083 Roseneath Avenue,|appartement 9, Alexandria, Virginie.
{20766}{20890}Le FBI considère que l'inculpé|est responsable de 14 meurtres ?
{20892}{20942}Oui, M. Le président.
{20967}{21063}Toutes ces affaires|ont été classées comme des suicides.
{21065}{21142}Nous croyons qu'il s'agissait de meurtres.
{21144}{21231}Vous croyez ?|Avez-vous des preuves recevables ?
{21233}{21337}Nous avons un enregistrement|où l'inculpé avoue ces meurtres.
{21339}{21491}Il les appelle ainsi, et il connaissait|des détails réservés à la police.
{21493}{21602}Une victime de ces soi-disant meurtres|s'est jetée sous un train.
{21604}{21673}Le quai était bondé. Cent témoins.
{21675}{21765}Personne ne l'a poussée.|Les plus proches étaient à dix mètres.
{21767}{21849}- Votre client était présent.|- Aussi connaît-il les détails.
{21851}{21924}- Expliquez-vous.|- Ces personnes sont mortes
{21926}{22035}parce que l'inculpé le voulait expressément.
{22037}{22136}- Il le voulait ?|- Il a reconnu être un tueur à gages.
{22138}{22221}Il recourt au pouvoir de suggestion|qu'il possède.
{22223}{22287}Il pousse ses victimes à se faire du mal.
{22289}{22407}- C'est à ne pas croire.|- Pouvez-vous me redire tout cela ?
{22409}{22527}Hier, l'inculpé a amené|un agent de police à s'immoler.
{22529}{22599}J'y ai assisté, ainsi que ces agents.
{22601}{22681}- Il a avoué. Nous demandons...|- M. Le président,
{22683}{22773}il est difficile d'établir|les preuves de cette affaire.
{22775}{22847}Nous demandons quelque temps|pour terminer l'enquête.
{22849}{22946}Nous voudrions que M. Modell soit jugé|pour ses aveux enregistrés.
{22948}{23005}Cet enregistrement, M. Modell ?
{23007}{23100}- Avez-vous avoué ces 14 meurtres ?|- Soyez simple.
{23150}{23234}Malheureusement, oui.|Quoique je ne m'en souvienne pas.
{23236}{23367}C'était une farce que mon client|a faite en état d'ébriété.
{23369}{23458}Une farce ? Il connaissait les détails|de toutes les affaires.
{23460}{23593}Robert regrette la situation fâcheuse|que son geste a provoquée.
{23616}{23680}Vous niez ces inculpations ?
{23709}{23790}Absolument. Je ne suis pas coupable.
{23962}{24016}Merci beaucoup.
{24018}{24078}Veuillez m'excuser un instant.
{24188}{24258}Vous me devez cinq dollars.
{24480}{24541}Votre lacet est défait.
{24564}{24624}Je vous ai poussé à regarder.
{24674}{24739}Comment faites-vous ?
{24885}{24935}Modell !
{24958}{25031}Je connais votre nom, et votre adresse.
{25690}{25751}J'ai trouvé deux ou trois choses|sur Modell.
{25753}{25884}Voyons, il a eu une scolarité moyenne|et a fait un service militaire moyen.
{25886}{25938}- Quelle branche ?|- Pas celle qu'il voulait.
{25940}{26034}Il voulait les forces d'intervention spéciale, puis les Bérets Verts.
{26036}{26107}Il a été refusé -|pas pour manque d'intelligence.
{26109}{26222}Il a fini employé à Fort Bragg.|Deux ans, puis renvoyé à la vie civile.
{26224}{26357}Savais-tu qu'il voulait entrer au FBI ?|Échec complet au test psychologique.
{26359}{26407}- Tu as une copie ?|- Oui.
{26409}{26483}Il a été taxé "d'égocentrisme aigu".
{26485}{26579}"Aucune considération pour les autres,|les perçoit comme des objets."
{26581}{26661}"Il se méfie à l'extrême de l'autorité."
{26663}{26713}Pourtant, il veut en faire partie.
{26715}{26800}Il a raconté une douzaine|de mensonges mégalomanes :
{26802}{26931}Qu'il était un maître d'arts martiaux,|formé par des ninjas au Japon.
{26933}{27027}On dit que les ninjas confondent|l'esprit de leurs adversaires.
{27029}{27139}- Parlons-nous de films de kung-fu ?|- Il a confondu le juge.
{27141}{27221}Il n'en avait pas besoin.|Nous n'avions rien.
{27223}{27306}Nous avions de quoi|passer la première audience.
{27308}{27365}Modell l'a envoûté.
{27367}{27436}Donne-moi une explication scientifique|des envoûtements.
{27438}{27523}C'est peut-être|une technique mentale d'un art martial,
{27525}{27641}le cerveau se bloque|à une cadence de la voix de Modell.
{27643}{27741}- Apparemment, sa voix est la clé.|- Son dernier emploi
{27743}{27809}a été une place de vendeur.
{27811}{27905}Les ninjas ne l'ont pas formé,|il n'a jamais quitté les États-Unis.
{27907}{27996}C'est un homme médiocre|qui rêve de grandeur.
{27998}{28086}Et nous l'encourageons.|Son échec au test -
{28088}{28215}s'il pouvait contrôler les personnes,|ce serait un agent du FBI,
{28217}{28279}un Béret Vert,|il serait aux forces d'intervention.
{28281}{28389}Il a peut-être acquis ce pouvoir|ces deux dernières années.
{28400}{28502}Quelle est ton idée ?|Comment expliques-tu le geste de Collins ?
{28504}{28598}Il est sain d'esprit, aucun trouble psychique...
{28600}{28682}Et il s'immole par le feu.|Comment ça se fait ?
{28684}{28793}Dois-je te dire que je crois Modell coupable ? Il l'est.
{28795}{28898}Je cherche une explication|moins banale que celle de l'envoûtement.
{28900}{28946}Il se moque bien de nous, Scully.
{29540}{29590}LAISSEZ-PASSER
{29998}{30101}Excusez-moi,|où se trouve le Service des Fichiers ?
{30103}{30172}Au 4ème étage, aile ouest.
{30174}{30224}Merci beaucoup.
{30621}{30673}SERVICE DES FICHIERS
{30737}{30799}Vous désirez ?
{30866}{30943}J'ai besoin de quelques informations,
{30987}{31037}Holly.
{31295}{31347}ATTENTION : PROPRIÉTÉ EXCLUSIVE DU FBI
{31349}{31447}Parfait. Laissez-moi le clavier une minute.
{31784}{31844}Je voudrais une copie de tout ça.
{31882}{31955}Et un café, quand vous aurez le temps.
{32132}{32269}Si je tenais celui qui vous a fait ça,|il le paierait cher.
{32666}{32758}- Je peux vous aider ?|- Non. Merci, nous...
{32760}{32817}Tout va bien.
{32900}{32994}Écoutez, nous sommes occupés, alors...
{32996}{33109}- Qui êtes-vous et que faites-vous ici ?|- Va te promener !
{33111}{33161}- Lâchez-moi !|- Tais-toi !
{33170}{33221}Holly, appelez la Sécurité.
{33256}{33325}Holly... c'est lui.
{33363}{33413}C'est votre agresseur.
{33415}{33465}Holly, appelez la Sécurité !
{33467}{33543}- Empêchez-le de me faire du mal.|- Tais-toi ! Holly !
{33545}{33589}- Holly...|- Holly !
{33718}{33800}- Sécurité.|- Incident au quatrième.
{33802}{33861}Non !
{33863}{33923}Rendez-lui les coups.
{34116}{34234}Monsieur...|Je suis affreusement désolée.
{34266}{34323}Je ne sais pas pourquoi j'ai...
{34325}{34375}Mon Dieu.
{34401}{34458}Je suis vraiment navrée.
{34522}{34587}Bon, sortez tous.
{34804}{34894}Que pourriez-vous|nous dire d'autre qui explique
{34896}{34994}pourquoi vous avez attaqué M. Skinner ?
{34996}{35098}C'est comme si je m'étais vue|de l'autre côté de la pièce.
{35115}{35183}En train... de faire ça.
{35188}{35271}Comme s'il était avec moi, dans ma tête.
{35296}{35346}Modell ?
{35366}{35448}- Je ne saurais le décrire autrement.|- Monsieur.
{35450}{35523}- Pouvons-nous parler dehors ?|- Oui.
{35525}{35585}Holly, excusez-nous un instant.
{35749}{35859}Les enregistrements montrent Modell|qui entre et sort inaperçu.
{35861}{35921}Il portait le mot "laissez-passer".
{35923}{35987}Les gardes ne se souviennent|même pas de lui.
{35989}{36090}Ce mystère explique pourquoi je porte|la marque d'un talon au visage ?
{36092}{36153}Je suis d'accord avec l'agent Mulder.
{36155}{36267}Je ne saurais l'expliquer, mais Modell est responsable de ces coups.
{36269}{36343}- Pourquoi s'intéresse-t-il tant à vous ?|- Pardon ?
{36345}{36430}Il n'a emporté que votre dossier.|Il a ignoré les autres.
{36432}{36535}- Il a ton adresse.|- Vous avez la sienne. Arrêtez-le.
{36537}{36630}Nous n'avons qu'un délit|d'entrée non autorisée.
{36632}{36679}C'est assez pour un mandat.
{36706}{36756}Police !
{36807}{36857}Police !
{36877}{36927}Modell !
{36990}{37088}- Lumière !|- Regardez-moi droit dans les yeux.
{37117}{37175}Droit dans les yeux.
{37177}{37227}Non, je vous en prie. Laissez-moi.
{37229}{37279}Esvengali.
{37336}{37365}MANDAT DE PERQUISITION
{37367}{37449}- Il n'y a personne.|- Fouillez l'immeuble.
{37451}{37525}Et ceux d'à côté, il aime regarder de loin.
{37527}{37617}Faites une fouille, j'interroge les voisins.
{37942}{38010}Scully, regarde ça.
{38012}{38059}"Un tourbillon mangue-kiwi."
{38061}{38097}COUP DE FOUET
{38099}{38168}Nous avons bien affaire à un fou.
{38229}{38346}Que pouvez-vous me dire d'autre ? Oui ?
{38348}{38408}Oui, à quelle date ?
{38474}{38530}Oui.
{38579}{38641}Merci beaucoup.
{38643}{38679}- Tegretol.|- Qu'est-ce que c'est ?
{38681}{38780}Pour les crises de Modell.|Il souffre d'épilepsie du lobe temporal.
{38782}{38860}Le cabinet de son docteur|reste discret au téléphone.
{38862}{38952}Mais on lui a prescrit ceci en avril 1994.
{38973}{39034}Les causes de l'épilepsie tardive ?
{39036}{39118}Lésion cérébrale, trouble neurologique, tumeur au cerveau...
{39120}{39230}Tumeur ? On relie les tumeurs au cerveau à des phénomènes parapsychiques.
{39232}{39325}- Ce n'est pas prouvé.|- Écoute-moi un instant.
{39327}{39460}Si le pouvoir de Modell était|une forme de psychokinésie ?
{39462}{39539}- Due à une tumeur ?|- Oui, toutes ces protéines !
{39541}{39663}Il récupère l'énergie qu'il dépense|en contrôlant les personnes.
{39665}{39767}Restons concrets,|si Modell avait une tumeur au cerveau,
{39769}{39830}son état de santé serait plus grave.
{39832}{39917}Il ne pourrait pas jouer avec nous|comme ça.
{39919}{39991}Justement, tout est là, peut-être.
{39993}{40043}- Quoi ?|- Il est à bout.
{40045}{40148}Il ne s'est pas laissé prendre,|il allait trop mal pour s'évader.
{40150}{40265}Pourquoi un tueur aussi doué|avouerait-il des meurtres déjà classés ?
{40267}{40381}- Il est peut-être mourant.|- Il veut disparaître dans la gloire.
{40383}{40453}Rien de discret : Un coup d'éclat.
{40555}{40605}Installez le détecteur.
{40661}{40739}- Allô ?|- Tiens, tiens, tiens.
{40741}{40820}Alors, Modell ? Comment va ?
{40822}{40875}Cela faisait longtemps.
{40877}{40929}Mais j'avais votre adresse.
{40931}{41035}Bel appartement.|Qui l'a décoré, le Grinch qui a volé Noël ?
{41037}{41132}Frank Burst,|le type qui a un chouette nom.
{41134}{41199}Dites, Mulder et Scully sont là ?
{41208}{41271}- Nous sommes là.|- Parfait.
{41284}{41349}Frank, combien pesez-vous ?
{41351}{41426}- Pardon ?|- Quel est votre poids environ ?
{41428}{41519}Du moment que tu parles...|Je ne sais pas, 85 ou 90 kilos.
{41521}{41621}Plutôt cent !|Un poids excessif pour votre taille.
{41623}{41688}Ne vous vexez pas,|vous êtes bâti comme un tonneau.
{41690}{41791}Attendez que mes pattes trapues|vous bottent. Où cela nous mène-t-il ?
{41793}{41882}C'est mauvais pour la santé,|surtout si vous fumez.
{41884}{42003}Vous devez boire de temps en temps,|manger trop gras. Des saucisses...
{42005}{42089}- Frank...|- Des oignons frits huileux.
{42091}{42167}Je vous vois jouant aux maracas|avec la salière !
{42174}{42248}Frank ! Frank, raccrochez.
{42259}{42326}Quoi, Modell ? Où voulez-vous en venir ?
{42328}{42390}C'est très mauvais pour les artères.
{42392}{42468}- Désastreux, FranK.|- Frank...
{42476}{42573}Des morceaux jaunâtres traversent|vos système sanguin,
{42575}{42643}ils collent aux parois de vos artères.
{42645}{42728}- Raccrochez.|- Ils compriment l'aorte.
{42730}{42771}- Le sentez-vous ?|- Allez.
{42773}{42838}- Sentez-vous votre aorte...|- Raccrochez !
{42840}{42881}- Reculez !|...se comprimer ?
{42883}{42933}- Des kilomètres...|- Raccrochez !
{42935}{42981}Reculez, j'ai dit !
{42983}{43035}- Raccrochez !|- Repérez l'appel !
{43048}{43097}- Mulder...|- Raccrochez !
{43099}{43149}... la maladie appelée pachyémie ?
{43151}{43258}Le sang épaissit|comme de la confiture de fraises.
{43260}{43332}- Repérez l'appel !|- Raccrochez !
{43340}{43430}- Raccrochez !|- Votre coeur s'arrête de battre.
{43587}{43631}Frank !
{43633}{43683}Vous mourez, Frank.
{43739}{43787}Frank ?
{43805}{43850}Hé, FranK !
{43932}{43997}Pas de pouls.|Appelez une ambulance.
{44054}{44191}Une ambulance au 3083 Roseneath Avenue. Arrêt cardiaque.
{44193}{44274}- Modell ?|- Hé, Mulder !
{44276}{44329}Comment va Frankie ?
{44340}{44422}Qu'est-ce que vous voulez vraiment ?
{44424}{44581}Un bon adversaire. Et ce n'est pas ce gros tas qui gît à vos pieds.
{44593}{44654}J'espère que c'est vous.
{44656}{44697}Pourquoi moi ?
{44699}{44793}J'ai lu votre dossier.|Vous êtes au top niveau.
{44795}{44895}Diplômé d'Oxford,|brillant à tous points de vue.
{44897}{44972}Vous savez ce qui me motive, pas vrai ?
{44999}{45064}Vous croyez percer|ce bon vieux Bob Modell à jour.
{45066}{45129}Bob Modell, ce bon vieux malade,|pas vrai ?
{45131}{45183}Vous êtes mourant, n'est-ce pas ?
{45185}{45289}Vous voulez tuer|quelques innocents avant de mourir ?
{45325}{45448}Pour la biologie, nous mourons tous.|Pour la Bible, il n'y a pas d'innocents.
{45450}{45540}Certains le sont plus que d'autres.|Dites-moi où vous êtes.
{45542}{45607}Vous voulez un numéro de téléphone ?
{45609}{45732}D'accord. Attendez... 555-0197.
{45753}{45849}C'est un téléphone public,|je n'y serai plus.
{45913}{46011}Vous l'avez tué pour rien,|espèce de malade ?
{46039}{46171}Moi ? Vous n'avez pas compris, Mulder ?|Ils se tuent tout seuls.
{46198}{46299}- D'où appelle-t-il ?|- D'une station d'essence.
{46301}{46432}Section 12000, Chain Bridge Road.|Un téléphone public, comme il a dit.
{46506}{46592}L'hôpital Fairfax est au bout de la rue.
{46594}{46659}La pharmacie Fairfax.
{46709}{46820}Pharmacie Fairfax.|Il doit avoir besoin de soins réguliers.
{46831}{46898}Allons voir.
{47011}{47058}HOPITAL FAIRFAX
{47250}{47318}Nous voyons l'entrée.
{47371}{47421}Allez-y.
{47577}{47629}Les voilà.
{47643}{47774}On a trouvé sa voiture. Moteur chaud, il doit être dans le bâtiment.
{47776}{47851}Entrées surveillées.|On attend ou on entre ?
{47885}{47944}Attendez.
{47946}{47991}- Attendez.|- Reçu.
{47993}{48135}Modell doit faire une IRM à 14 h 30.|C'est maintenant.
{48141}{48225}- Que voulez-vous faire ?|- Je devrais y aller seul.
{48227}{48266}- Pourquoi ?|- Mes hommes le débusqueront.
{48268}{48396}Et si Modell tourne l'un d'eux|contre les autres dans un hôpital bondé ?
{48422}{48501}Nous devrions lui donner ce qu'il veut.
{48503}{48593}- Toi.|- Séparément, nos chances augmentent.
{48595}{48710}Je porterai un micro,|vous saurez ce qu'il fait et où il est.
{48712}{48796}- Avez-vous une radio ?|- J'ai ce qu'il vous faut.
{48798}{48830}YEUX ET OREILLS
{49146}{49241}Une caméra infrarouge.|Autant dire qu'elle voit dans le noir.
{49243}{49372}Il  sert au désamorçage des bombes,|un seul agent s'expose. Vous voyez ?
{49446}{49511}Je peux prendre Playboy Channel ?
{49605}{49670}Souris, Scully.
{49819}{49868}- Prends-le.|- Non.
{49870}{49979}Je veux être sûr|de ne mettre en joue que Modell.
{50066}{50104}Bon, j'entre en action.
{50357}{50437}FBI. Continuez votre travail.
{50459}{50517}Scully, tu me reçois ?
{50519}{50565}Je suis là, Mulder.
{50567}{50630}Tout est normal.
{50632}{50729}- Équipe SWAT, attendez dehors.|- L'équipe attend.
{51093}{51120}Mulder !
{51122}{51166}- Deux coups de feu.|- Équipe SWAT !
{51168}{51236}Pas encore. Tout le monde court. FBI !
{51238}{51331}- Je vais voir ce qui se passe.|- Je te perds.
{51333}{51383}Mulder. Agent Mulder !
{51407}{51457}Attendez, agent Scully.
{51485}{51560}Vous recevez l'image ?
{51872}{51901}Que s'est-il passé ?
{51903}{52056}Le garde a tué le technicien|avant de se tuer. Son arme n'est plus là.
{52061}{52121}Avertissez vos hommes|que Modell arrive.
{52123}{52216}Le suspect est armé|et se dirige peut-être vers une sortie.
{52218}{52286}- Reçu.|- Tireurs en position.
{52288}{52369}Mulder, attends. Approche-toi de l'écran.
{52382}{52451}- Là ?|- Oui, oui, là.
{52496}{52571}Voilà, la masse dans son lobe temporal.
{52592}{52669}- Ici ?|- Tu avais raison.
{52684}{52807}Cherche, la fiche clinique de Modell|ne doit pas être loin.
{52924}{52970}TUMEUR
{53028}{53139}Nous avons vu juste.|Modell meurt, il n'a rien à perdre.
{53141}{53215}Mulder, va-t'en. Pars.
{53328}{53378}Mulder ?
{53432}{53472}Mulder !
{53474}{53514}Mon Dieu !
{53596}{53731}Ils sont à trois portes d'ici.|Il y a six chambres de soins intensifs.
{53733}{53819}En gazant le couloir,|nous pourrions tuer ces malades.
{53910}{54003}Pourquoi fait-on tout ce qu'il veut ?
{54005}{54055}Attendez mon signal.
{54093}{54143}La voie est libre.
{55083}{55127}Mulder.
{55411}{55463}Merci d'être venue.
{55465}{55569}Il y a une douzaine d'agents|dans le couloir.
{55571}{55631}Et trente autres dans le parking.
{55663}{55716}Quelle réunion !
{55718}{55846}Quelles que soient vos intentions,|votre plan échouera.
{55848}{55906}Vous ne connaissez pas mon plan.
{56424}{56516}Deux guerriers de force égale|se battent à mort.
{56532}{56670}L'un étudie le budojaponais :|L'art de la guerre.
{56684}{56809}Le budo apprend au guerrier|à rester au-dessus du combat.
{56836}{56944}En d'autres mots,|à mépriser sa propre mort.
{57038}{57123}C'est pour ça que le guerrier budo|gagne toujours.
{57153}{57222}Je suis un guerrier budo.
{57224}{57284}Je ne crains pas la mort.
{57326}{57395}Alors... je vous invite...
{57442}{57503}à tirer une fois sur moi.
{57575}{57640}Une chance sur six.
{57771}{57836}Appuyez une seule fois.
{57919}{57991}Attends. Mulder, écoute.
{57993}{58056}Il y a de l'oxygène pur dans la chambre.
{58058}{58165}Imagine ce qui se passerait si tu tirais...
{58318}{58368}Du gâteau.
{58415}{58465}A vous.
{58531}{58603}- Mulder, non.|- Mulder, oui.
{58636}{58701}- Allez.|- Écoute-moi.
{58724}{58855}Donne-moi ton arme. Arrêtons tout cela.|Toi et moi, nous sortirons d'ici...
{58857}{58929}Non ! Bon Dieu ! Salaud !
{58931}{58996}Mulder, donne-moi...
{59298}{59363}Mulder, pourquoi fais-tu ça ?
{59399}{59495}- Tu es au-dessus de tout ça.|- A vous, Scully, jouez le jeu.
{59497}{59584}- Appuyez, Mulder.|- Lutte, tu peux le battre.
{59586}{59644}Allez ! Appuyez, Mulder.
{59646}{59746}J'ai lu qu'elle vous a tiré dessus.|Rendez-le-lui. Tuez-la !
{59748}{59847}- Je vais vous tuer, Modell.|- Appuyez, et ce sera à mon tour.
{59849}{59916}Scully, cours !
{59956}{60013}Scully...
{60255}{60339}FBI ! Couchez-vous, couchez-vous !
{61584}{61656}On ignore combien de temps il tiendra,
{61658}{61733}mais il ne reprendra pas conscience.
{61780}{61892}Nous croyions qu'il se soignait,|nous nous trompions.
{61894}{61945}- Pardon ?|- Lis sa fiche clinique.
{61947}{62067}On évaluait ce qui lui restait à vivre,|mais il refusait tout traitement.
{62069}{62172}Sa tumeur était opérable,|mais il a refusé de la faire enlever.
{62174}{62249}- Pourquoi ?|- Je crois que tu avais raison.
{62278}{62364}Il a toujours été... médiocre.
{62396}{62484}Il se sentait enfin quelqu'un d'important.
{62684}{62785}Ne perdons pas une minute de plus|avec lui.
{63486}{63569}Sous-titrage Visiontext : Anne Bruant
{63897}{63936}C'est moi qui l'ai fait !
{63985}{64035}FRENCH
