{184}{285}ESPACE AERlEN lRAQUlEN,|37EME PARALLELE, AUJOURD'HUl
{602}{664}Base de contrôle, ici patrouilleur six.
{669}{770}Demande d'identification|d'un objet à 40 km de ma position.
{798}{866}Aucun signe d'un objet.|Votre position est exacte?
{1041}{1092}Il était là il y a à peine une seconde.
{1150}{1224}VOUS SUBlSSEZ UNE ATTAQUE!!
{1398}{1433}JE L'Al DANS MON VlSEUR.
{1499}{1547}TOUCHE! JE L'Al EU!
{1637}{1761}HAKKARl, TURQUlE,|BASE DE L'OTAN, FRONTlERE lRAQUlENNE
{2179}{2290}Croissant Sud à Croissant Rouge.|Un avion s'est écrasé dans notre périmètre.
{2293}{2364}Nous n'avons rien dans le ciel à présent.
{2367}{2448}Nous avons quelque chose ici.|Nous allons voir sur place.
{2541}{2603}Medevac Un, ici Croissant Rouge.
{2606}{2711}Croissant Sud signale qu'un avion|a été abattu dans sa région.
{2750}{2810}AUX FRONTlERES DU REEL
{3097}{3159}ACTlVlTE PARANORMALE
{3288}{3339}LE GOUVERNEMENT NOUS MENT
{3749}{3808}LA VERlTE EST AlLLEURS
{3925}{4053}OOH20 HEURE CENTRALE|ROUTE 100, REAGAN, TENNESSEE
{4170}{4339}Ici le Grand Ole Opry sur WSM Radio 650.|Offert par la Poudre Maux de Tête Goody's.
{4342}{4422}Quand la nuit a été longue|et que vous avez trop fait la fête,
{4425}{4566}Ia Poudre Goody's vous remet|d'aplomb. Vous avez ma parole.
{4772}{4868}Ca ressemblait à un cigare,|des lumières rouges et vertes. Très rapide!
{4871}{4944}J'en ai vu trois voler|au-dessus du comté de Chester.
{4947}{5017}Ils avaient six soldats|à leurs trousses sur la 22.
{5042}{5127}J'en vois un! Au-dessus du château d'eau.
{5130}{5179}Je le vois aussi!
{6944}{7059}D'après ce que dit le camionneur, il est|possible qu'il ait tiré sur un puma.
{7062}{7088}C'est concevable.
{7091}{7164}La météo a annoncé hier soir
{7167}{7243}qu'avec les conditions|atmosphériques dans cette région
{7246}{7292}il y avait un risque d'orage.
{7295}{7319}C'est possible.
{7474}{7554}La foudre aurait pu frapper le camion,
{7557}{7610}ce qui aurait provoqué la panne électrique.
{7613}{7662}C'est vraisemblable.
{7665}{7732}Et tu sais, il y a un marais un peu plus loin.
{7758}{7862}Ces lumières que le camionneur a vues|pourraient être des feux follets.
{7881}{7951}- Des feux follets?|- C'est un phénomène naturel.
{7954}{8067}La décomposition produit de la phosphine|et du méthane qui prennent feu
{8070}{8124}et donnent des flammes bleues en boules.
{8127}{8193}C'est ce qui m'arrive|quand je mange un hot-dog.
{8206}{8302}Comment ce gaz aurait-il pu|pousser 12 témoins, dont des policiers,
{8305}{8356}à l'hystérie collective?
{8359}{8415}J'ai enquêté sur d'autres cas similaires.
{8418}{8501}Chesapeake Bay, le lac Okobogee,|Zone 51 dans le Nevada.
{8504}{8557}Jamais avec autant de preuves à l'appui.
{8560}{8673}Des résidus d'échappements, un taux de|radiation cinq fois supérieur à la norme.
{8676}{8734}Aucune de ces preuves n'est concluante.
{8737}{8811}La question, c'est pourquoi ce camionneur?
{8814}{8863}N'est-il pas plus plausible
{8866}{9010}que le conducteur, victime de l'hystérie|collective, ait tiré sur des hallucinations?
{9013}{9077}Trop de temps|sur la route peut jouer des tours.
{9079}{9128}Oui, ça peut jouer des tours.
{9166}{9215}Mais pas comme celui-ci.
{9246}{9316}J'ai déclenché|ces chronomètres au même moment.
{9353}{9408}Je ne sais pas pourquoi ils me retiennent.
{9431}{9538}Ils m'accusent d'avoir tiré sur une route|du comté mais c'est n'importe quoi.
{9561}{9618}Je suis un vétéran,|je sais me servir d'une arme.
{9621}{9670}M. Ranheim,
{9673}{9780}pourriez-vous développer votre|déposition d'hier soir concernant l'OVNl?
{9783}{9832}Il était rond.
{9887}{9936}Comme une soucoupe.
{9958}{10007}Avec... des lumières vertes et oranges.
{10010}{10079}Hier soir, vous avez dit noir,|en forme de cigare.
{10082}{10131}Je n'ai pas demandé à ce que ça m'arrive.
{10234}{10364}Je veux juste déposer ma cargaison de pièces|détachées de voitures et tout oublier...
{10534}{10583}J'aimerais vous demander,
{10586}{10645}depuis combien de temps|avez-vous cette toux?
{10746}{10772}Pourquoi?
{10775}{10839}Je me demande.|Vous êtes un ancien combattant.
{10864}{10964}- Qu'est-ce que ça a à voir?|- La toux, la fièvre, les rougeurs.
{10967}{11020}Ce sont les symptômes|du syndrome du Golfe.
{11023}{11161}- Je n'étais pas dans le Golfe.|- Alors depuis quand avez-vous ça?
{11285}{11334}Depuis ce truc hier soir.
{11425}{11479}M. Ranheim? Commissaire Rivers.
{11482}{11595}Veuillez excuser ce malentendu.|Votre camion vous attend. Vous êtes libre.
{11598}{11671}- J'aimerais examiner le camion.|- Ce n'est pas nécessaire.
{11674}{11770}C'est le témoin présumé d'un OVNl.|Il doit y avoir des traces sur le camion.
{11773}{11853}- Si vous voulez bien...|- Nous ne vous aiderons pas d'avantage.
{11856}{11939}- Nous ne coopérerons plus à votre enquête.|- Pourquoi?
{11966}{12030}Partez... c'est tout.
{12188}{12237}Non... pas ici.
{12495}{12544}VOlTURES DE LOCATlON
{12583}{12671}Le commissaire s'est fait acheter.|Ranheim cache quelque chose.
{12674}{12739}- Ranheim est malade.|- ll l'est depuis hier soir.
{12742}{12791}Je peux emprunter votre stylo?
{12827}{12895}Tu crois que le syndrome du Golfe|est causé par des OVNl?
{12898}{12975}Les soldats voient souvent|des OVNl en temps de guerre.
{12998}{13057}Merci.
{13060}{13208}Mulder, il s'agit surtout|d'avions militaires secrets.
{13211}{13351}C'est ce qu'ont dit les soldats en lraq.|Des traces de carburant d'un avion secret.
{13407}{13514}Il y a une base à Little Rock. Tu crois que|c'est d'un avion qu'il s'agissait?
{13517}{13637}L'armée l'a démenti. Mais ça expliquerait|les symptômes de Ranheim.
{13640}{13679}C'est possible.
{13682}{13756}Je vais en parler à des amis|quand on rentre à Washington.
{13759}{13829}L'armée ne va pas te parler|de ses avions secrets.
{13832}{13946}C'est un groupe qui surveille le|gouvernement. Il publie Les Francs-Tireurs.
{13949}{14041}Ils ont des informations concernant des|opérations et des armes secrètes.
{14044}{14108}Certaines de leurs théories|font carrément peur.
{14132}{14203}Ecoute ça, Mulder.
{14206}{14276}- J'ai rencontré l'assassin de Kennedy.|- Sans blague?
{14279}{14372}Ouais. Il dit qu'il était déguisé|en flic sur le terre-plein.
{14375}{14507}Mulder, écoute ça. Vladimir Zhirinovsky, le|chef des sociaux-démocrates russes?
{14510}{14591}Il a été mis en place par l'esprit|le plus maléfique de ce siècle.
{14594}{14643}Casimir?
{14667}{14728}La ClA.
{14731}{14789}Ta partenaire est-elle du genre sceptique?
{14820}{14869}Elle est bien.
{14872}{14974}Ne croyez-vous pas que la ClA, affaiblie|depuis la fin de la guerre froide,
{14977}{15041}aimerait retrouver son vieil ennemi?
{15043}{15122}Vous attribuez trop de|mérite au gouvernement.
{15158}{15264}- ll ne contrôle même pas le déficit...|- Les Francs-Tireurs.
{15267}{15340}Comment pourrait-il organiser un|complot aussi élaboré?
{15343}{15407}- Elle est vraiment bien.|- Calme-toi, Frohike.
{15409}{15498}Il ne s'agit pas d'une bande d'idiots|dans une maison peinte en blanc.
{15501}{15620}Mais d'un gouvernement dans le|gouvernement, au courant du moindre geste
{15623}{15712}- Et comment font-ils ça?|- Je vais vous montrer. Vous avez 20 dollars?
{15776}{15815}Je vais voir.
{16023}{16072}Hé!
{16192}{16288}Il y a d'autres méthodes. Ils utilisent cette|languette magnétique pour nous suivre.
{16291}{16427}On passe sous un détecteur de métaux à|l'aéroport et ils savent tout ce qu'on a.
{16430}{16536}- Détruire un billet est un crime fédéral.|- La languette est là pour éviter les faux.
{16539}{16603}D'autres pays la mettent à l'extérieur.
{16606}{16706}Bon! Ca suffit.|Que savez-vous sur le syndrome du Golfe?
{16709}{16799}- L'Agent Orange des années 90.|- Des obus à base d'uranium appauvri.
{16802}{16904}Avez-vous entendu parler d'avions|secrets durant la guerre du Golfe?
{16907}{17021}Pourquoi exposer un avion secret à une|armée de l'air ennemie qui a déjà la frousse?
{17024}{17103}Et la présence d'OVNl durant cette période?
{17106}{17173}Le syndrome du Golfe causé par des OVNl!|Elle est bonne!
{17176}{17246}Tes théories sont encore|plus tordues que les nôtres!
{17310}{17389}Je n'ai jamais rencontré|personne d'aussi paranoïaque.
{17392}{17471}Comment peux-tu croire ces théories?
{17474}{17563}Il est tout à fait plausible que|quelqu'un puisse te trouver bien.
{17678}{17752}As-tu vu comment ils ont|répondu à ce téléphone?
{17793}{17921}Ils croient probablement être sur|écoute et qu'ils se font suivre.
{17923}{18039}Ils s'imaginent tout ça. Ca leur donne|l'impression d'être important...
{18125}{18186}Qu'y a-t-il?
{19771}{19820}Allô?
{20236}{20330}C'est le début de la saison|d'entraînement printanière.
{20333}{20390}Alors que faisons-nous ici?!
{20431}{20493}Vous avez raté votre vocation,|c'est ça, M. Mulder?
{20527}{20610}On pourrait aller voir|un match à Candleton Yards.
{20632}{20704}Bien entendu, on ne pourra pas|s'asseoir ensemble.
{20707}{20826}Quel dommage. Vous auriez probablement|pu nous avoir de bonnes places.
{20829}{20870}Ouais...
{20873}{20918}Dans n'importe quel stade.
{20985}{21043}C'est juste un touriste.
{21048}{21146}Dans notre métier,|rien n'est comme il n'y paraît.
{21176}{21283}Suis-je sur une piste? J'enquêtais|sur un camionneur qui a vu un OVNl.
{21286}{21401}Et puis je trouve du matériel de surveillance.|Qui est derrière les micros?
{21467}{21513}Pourquoi ne me le dites-vous pas?
{21777}{21816}Suis-je sur une piste?
{21876}{21925}Une piste dangereuse.
{22067}{22122}TRANSMlSSlON lRAQUlENNE lNTERCEPTEE
{22617}{22692}Le camion est bidon.|Le conducteur, Ranheim, aussi.
{22695}{22744}J'ai vérifié son bon de transport.
{22747}{22863}Le camion est censé transporter 108 cartons|de pièces détachées pesants 1410 kilos.
{22866}{22988}Sa marchandise a été pesée trois fois ce|soir-là. Et elle pesait 2320 kilos.
{22991}{23070}Il y a quelque chose dans ce camion,|et pas des pièces détachées.
{23073}{23138}Et, bien sûr, personne ne l'a signalé.
{23141}{23205}Et Ranheim a menti|à propos de la guerre du Golfe.
{23208}{23266}Son vrai nom est Frank Druce.
{23269}{23323}J'ai eu du mal à trouver cette info.
{23326}{23419}Il était béret noir, aux services secrets|à Mosul, en lraq du nord.
{23422}{23509}Et il n'est pas tombé malade|à cause de ce qu'il a vu l'autre soir.
{23512}{23614}Il a subi trois traitements|à l'hôpital cette année.
{23617}{23644}On le tenait!
{23647}{23705}On le tenait et on l'a laissé filer.
{23799}{23890}Il y a quatre jours, un pilote de l'armée|iraquienne a descendu un OVNl.
{23893}{23996}Les débris, et probablement les|occupants, ont été récupérés par l'armée.
{23999}{24056}Ranheim était l'homme parfait
{24059}{24187}pour escorter les débris, et les corps, hors|d'lraq vers un laboratoire des Etats-Unis.
{24190}{24287}Ca expliquerait pourquoi le camion|pesait plus qu'il aurait dû.
{24290}{24339}Dans le passé, l'armée a transporté
{24342}{24457}par camions banalisés des équipements et|des armes dangereuses à travers le pays.
{24460}{24559}- Je parle comme les Francs-Tireurs.|- Où as-tu trouvé ces informations?
{24562}{24643}Disons que je tiens ça d'une source|qui sait de quoi elle parle.
{24703}{24752}Dis-m'en plus.
{24755}{24816}Je sais juste qu'il nous a évité des problèmes.
{24819}{24868}Comment peux-tu en être sûr?
{24871}{24954}On est au FBl et il y a des micros partout.|Comment expliques-tu ça?
{24957}{25035}Je pense tout simplement|que rien n'est comme il n'y paraît.
{25038}{25156}Exactement! Et si ça se trouve,|ta source est derrière les micros.
{25159}{25208}Il ne m'a jamais menti.
{25211}{25275}Je ne trahirai pas sa confiance. J'ai foi en lui.
{25278}{25337}Mulder, tu es le seul en qui j'aie foi.
{25362}{25434}Alors tu vas devoir me faire confiance.
{25464}{25539}Sais-tu où se trouve le camion maintenant?
{25542}{25591}Il se dirige vers l'ouest.
{25594}{25643}En direction du Colorado.
{25646}{25716}On va l'intercepter et voir|ce qu'il transporte.
{25719}{25831}Je vais chercher mes affaires. Je te rejoins|chez toi dans une heure. D'accord?
{26238}{26288}J'ai coupé le courant.
{26497}{26600}- Vous risquez d'être vu en venant ici.|- Ceci est trop important.
{26634}{26736}Cette photo a été prise|par un officier à Fort Benning, en Géorgie.
{26739}{26814}17 OVNl ont été aperçus en une heure.
{26817}{26889}Est-ce là qu'ils gardent les débris iraquiens?
{26892}{26941}Les OVNl surveillent-ils la région?
{26982}{27031}C'est sympa chez vous.
{27131}{27239}Attendez. Je voulais juste... vous remercier.
{27242}{27341}Vous m'avez beaucoup fait avancer,|sans rien demander en échange.
{27344}{27403}Et je sais que vous avez pris|de grands risques.
{28096}{28176}C'est la meilleure preuve|photographique que j'aie jamais vue.
{28179}{28249}Les photos du GulfBreeze|étaient clairement truquées.
{28252}{28342}Mais là il s'agit de preuves sérieuses|amassées par le gouvernement
{28345}{28411}au plus haut niveau de confidentialité.
{28414}{28500}Le camion était un appât pour|détourner l'attention des curieux
{28503}{28569}de Fort Benning, où se trouve l'OVNl iraquien.
{28572}{28667}- ll faut immédiatement aller en Géorgie.|- Cette photo est truquée.
{28670}{28695}Quoi?
{28698}{28747}Regarde.
{28781}{28872}L'ombre de ce soldat est censée|être produite par les lumières de l'OVNl.
{28875}{28962}Mais elle part dans la direction|opposée à la position de l'engin.
{28965}{29058}Ca pourrait être une lumière|hors caméra qui crée cette ombre.
{29061}{29153}Regarde de près la couleur|de la lumière reflétée sur le pare-brise.
{29156}{29287}Elle devrait être du même rouge que celle de|l'OVNl, mais elles ne correspondent pas.
{29290}{29398}Le pare-brise est peut-être teinté,|ou ce sont les conditions atmosphériques.
{29401}{29496}- Mulder, on devrait la faire analyser.|- Tu es décidée à ne pas le croire!
{29499}{29550}Et toi tu es trop résolu à le croire!
{29553}{29602}Je suis résolu à suivre une piste
{29605}{29708}qui pourrait prouver l'existence d'entités|biologiques extraterrestres.
{29711}{29740}- Ecoute...|- Non!
{29743}{29788}Vas-tu m'écouter?!
{29823}{29948}Je n'ai jamais rencontré quelqu'un d'aussi|passionné et dévoué à une cause que toi.
{29951}{30031}C'est si intense que|c'en est parfois aveuglant.
{30034}{30143}Mais d'autres personnes, qui savent cela|également, te surveillent, et,
{30159}{30273}tandis que moi je respecte et j'admire ta|passion, eux l'utiliseront contre toi.
{30324}{30373}Mulder, on finira par trouver la vérité.
{30389}{30438}Mais il y aura aussi des mensonges.
{30482}{30531}Merci.
{30626}{30709}08H30 COTE EST|SlEGE DU FBl, WASHlNGTON
{31800}{31906}J'ai fait analyser la photo|par le FBl. Elle avait l'air authentique.
{31909}{32033}Le grain de la photo correspond au ton et à la|densité... Ie niveau de couleur, les ombres...
{32036}{32126}Puis j'ai remarqué ceci.|La lune est à moitié pleine.
{32129}{32251}J'ai fait agrandir le reflet par 25.|Voici de nouveau la lune.
{32254}{32303}Un quart pleine.
{32306}{32395}La fenêtre n'aurait même|pas pu refléter la lune à cet angle.
{32398}{32474}Tu avais raison, Scully. Elle est truquée.
{32477}{32526}Il a essayé de nous tromper.
{32534}{32583}On est seul à présent.
{32610}{32659}On ne peut faire confiance à personne.
{32680}{32762}Ils se sont donnés beaucoup de mal|pour nous induire en erreur.
{32765}{32852}Il y a quelque chose que|personne n'est censé découvrir.
{33195}{33261}Pourquoi n'êtes-vous pas|parti pour Fort Benning?
{33278}{33327}La photographie était truquée.
{33351}{33458}Au moins vous ne m'insultez pas|en faisant semblant d'être étonné.
{33461}{33576}Au contraire, vous méritez d'être félicité.|Cette photo a été conçue par des spécialistes.
{33579}{33634}- Je vous croyais mon allié.|- Je le suis.
{33637}{33736}Imaginez qu'Eisenhower ait dit aux alliés|que le jour-J aurait lieu en Belgique.
{33739}{33830}M. Mulder, je mets ma vie en danger|chaque fois que je vous parle!
{33930}{34013}J'ai pris part|aux mensonges les plus insidieux
{34016}{34092}et j'ai été témoin d'actes|que même un fou n'oserait imaginer.
{34095}{34210}J'ai passé assez d'années|à vous observer du haut... de ma position,
{34213}{34284}pour savoir que je pouvais|vous faire confiance.
{34287}{34365}- Pourquoi m'avoir menti?|- Pour détourner votre attention.
{34390}{34501}Vous et Scully êtes d'excellents enquêteurs,|et votre motivation est juste.
{34504}{34606}Toutefois, il existe encore des secrets|qui devraient rester secrets.
{34609}{34684}Des vérités que les gens ne sont|pas encore prêts à entendre.
{34687}{34744}Qui êtes-vous pour décider cela à ma place?
{34766}{34863}La réaction du monde à une telle révélation|serait extrêmement dangereuse.
{34866}{34957}Dangereuse?|Vous voulez dire son indignation?
{34960}{35041}Comme son indignation|devant l'assassinat de Kennedy,
{35044}{35132}ou les expériences faites sur des|patients incurables. Le Watergate,
{35135}{35241}Ia Contra iranienne, Roswel...|Y aura-t-il une fin à ces mensonges?!
{35311}{35418}J'imagine que non, pas tant que les gens|comme vous décideront de ce qui est vrai.
{35462}{35593}La transcription du dossier iraquien,|elle était vraie, n'est-ce pas?
{35596}{35655}Pourquoi avoir pris la|peine de me la montrer?
{35671}{35741}Je savais que vous aviez|compris à propos du camion.
{35744}{35831}Donc je savais que je finirais|par devoir détourner votre attention,
{35834}{35883}que je serais obligé de vous mentir.
{35886}{36004}Et un mensonge, M. Mulder, est toujours plus|convaincant quand il est entouré de vérités.
{36093}{36142}Mulder!
{36161}{36226}Si le requin arrête de nager, il meurt.
{36311}{36360}N'arrêtez pas de nager.
{36406}{36486}Je ne suis pas derrière votre surveillance,
{36489}{36544}mais je sais qu'ils vous écoutent toujours.
{38663}{38712}Mulder!
{38748}{38805}Tu es là?
{38872}{38936}Scully. Je suis content que tu sois passée.
{38939}{39004}J'ai réfléchi à toute cette histoire.
{39007}{39107}Tu avais raison. Je crois qu'ils ont gagné|et on devrait passer à autre chose.
{39507}{39579}IL FAUT TROUVER LE CAMlON
{39628}{39688}Je crois que tu as raison cette fois-ci, Mulder.
{40276}{40335}Bon, ne le lâchez pas.
{41109}{41158}Hé!
{41232}{41313}09H16 COTE EST|AEROPORT DE DULLES, WASHlNGTON
{41316}{41417}Voilà. Un aller-retour à Chicago.|Je vous rends votre carte.
{41420}{41481}Et l'avion partira de la porte 35.
{41484}{41577}J'aimerais aussi un aller simple à Los|Angeles, avec une escale à Las Vegas.
{41580}{41625}Et je paierai en liquide.
{43065}{43166}11H30 COTE OUEST,|AEROPORT McCARRAN, LAS VEGAS
{43537}{43608}J'ai appelé tous nos bureaux|à l'ouest du Colorado.
{43611}{43699}J'ai passé trois heures au téléphone.|Je ne parle pas japonais,
{43702}{43801}mais je crois qu'on m'a dit de me|mettre du sushi là où je pense!
{43839}{43899}Et moi je suis sourde car|ils m'ont mise en attente.
{43902}{43972}Au moins on est sûr qu'ils|n'ont pas localisé ton appel.
{43975}{44043}Je n'ai pas trouvé le camion.|Tu as quelque chose?
{44046}{44121}Oui. Il se dirige au nord-est sur la l-90.
{44124}{44192}Il nous faut deux billets pour Seattle.
{44309}{44362}Si tu y penses.
{44365}{44479}Ce camion a traversé l'Amérique.|Les gens l'ont doublé sur la route.
{44482}{44595}Ils ont probablement cru qu'il transportait|des pièces détachées ou des meubles...
{44598}{44707}Personne n'aurait jamais soupçonné qu'il|transportait un engin d'un autre monde.
{44710}{44751}Le voilà.
{45610}{45686}Mulder, nous suivons|ce camion depuis plusieurs heures.
{45722}{45814}Il sait peut-être que nous le suivons|et il nous met sur une fausse piste.
{45817}{45870}Si c'est le cas...
{46377}{46436}- Est-ce que ça va?|- Oui.
{46741}{46798}Ranheim!
{47755}{47804}Scully!
{47910}{47946}Mon Dieu!
{47949}{48052}C'était une entité biologique|extraterrestre, vivante.
{48055}{48132}Où est-elle passée?
{48135}{48247}Je crois que nous venons d'être|témoins d'une opération de sauvetage.
{48674}{48738}Mon Dieu, Mulder, je n'arrête pas de trembler.
{48770}{48838}Ce qui vient de se passer,|ça correspond au profil?
{48856}{48910}Tu me demandes si c'était réel?
{48913}{48966}S'il s'agissait bien d'un OVNl?
{49070}{49119}Non. C'était un autre coup monté.
{49228}{49292}Mais comment ont-ils|pu générer une telle énergie?
{49317}{49392}Quelque chose dont on a|jamais entendu parler.
{49395}{49497}Peut-être des hélicoptères furtifs avec|intensité lumineuse ultracourte...
{49500}{49560}Il n'y a aucune preuve qu'il s'agit d'un OVNl.
{49563}{49657}Ils ont créé ce spectacle pour|détourner notre attention à nouveau.
{49661}{49722}Est-ce que ça n'aurait pas été plus facile de...
{49725}{49800}De nous tuer.|Ouais, je me demandais la même chose.
{49831}{49924}Mais peut-être qu'ils m'utilisent|contre moi-même, comme tu l'as dit.
{49927}{50055}Je suis si résolu à croire, que j'accepterais|la première conclusion qui vient à l'esprit.
{50146}{50198}Nous n'avons plus aucune piste.
{50236}{50278}Personne à qui nous adresser.
{50281}{50363}Il reste toujours un participant|qui ne nous a pas encore menti.
{50366}{50425}Mais on ne peut pas vraiment s'adresser à lui.
{50428}{50487}Leverlay et Priest Rapids?
{50519}{50568}Rive-est de la rivière Columbia.
{50595}{50667}Avez-vous envoyé un|enquêteur sur le terrain?
{50670}{50739}Et pouvez-vous corroborer?
{50742}{50798}O.K, Nick, merci beaucoup.
{50801}{50918}J'ai appelé des organisations qui ont des|lignes ouvertes pour les témoins d'OVNl.
{50921}{50981}Le Centre d'études d'OVNl à Chicago,
{50984}{51098}MUFON, NlCAP. Elles n'ont jamais connu|une période d'activité aussi intense.
{51101}{51178}Ca a commencé au Tennessee,|où Ranheim en a aperçu un.
{51181}{51250}Les témoignages suivent|le passage du camion.
{51253}{51302}Et après le coup monté d'hier...
{51305}{51347}Regarde ceci.
{51374}{51438}Sept témoins à Mattawa, Washington.
{51441}{51503}- C'est à 160 km.|- Des extraterrestres?
{51506}{51591}On dirait qu'ils veulent|retrouver leur collègue.
{51669}{51744}On a fait le tour complet|de Mattawa deux fois.
{51747}{51796}Il n'y a rien à voir.
{51882}{51919}Que se passe-t-il là-bas?
{52408}{52467}Ca veut dire bonjour|en langage intergalactique.
{52470}{52548}- Ca veut dire "salut, frère de l'espace."|- Je vois.
{52551}{52602}- Que faites-vous?|- Une soirée OVNl.
{52605}{52703}- Vous avez vu des OVNl?|- Deux fois. L'électricité les attire.
{52706}{52772}Ils planent au-dessus|de la centrale électrique.
{53148}{53203}Voilà. C'est Ranheim.
{53364}{53451}Cet endroit doit être muni de systèmes|de sécurité très perfectionnés.
{53454}{53533}C'est exactement le genre|de défi qui les attire.
{53536}{53585}Qui?
{53755}{53842}- Les Francs-Tireurs.|- C'est Mulder. Arrête d'enregistrer.
{53892}{53941}- Voilà. C'est fait.|- Eteins!
{53944}{53979}J'ai dit que c'était fait!
{53982}{54027}Est-ce que ça vous plairait d'avoir
{54030}{54131}Ia première véritable photo|d'une entité biologique extraterrestre?
{54134}{54224}Arrête! Un EBE?!|Qu'est-ce que ça va nous coûter?
{54227}{54278}Trouve-moi|quelques numéros d'identification.
{54285}{54358}LAlSSER-PASSER,|USlNE DU NORD-OUEST, MATTAWA
{54421}{54475}Braidwood et Stefoff.
{54531}{54578}Vos numéros d'identité?
{54581}{54616}7-5-9-3.
{54619}{54655}5-3-1-1.
{54658}{54719}Veuillez ouvrir le coffre, s'il vous plaît.
{55051}{55100}Garez-vous dans le couloir 4.
{55132}{55181}Merci.
{55366}{55415}Attendez!
{55466}{55510}Portez ça.
{55553}{55614}Allez-y.
{55969}{56051}Langly n'a pas pu obtenir|l'accès au 6ème, c'est pourquoi...
{56166}{56227}NlVEAU 6|ACCES AU PERSONNEL AUTORlSE
{56456}{56543}- Nous devons retourner à cette porte-là.|- On aura l'air suspect.
{56546}{56648}- Alors il faut trouver une autre porte.|- Mulder, ils nous arrêteront.
{56705}{56780}- Veuillez me suivre, s'il vous plaît?|- On s'est perdu...
{56783}{56836}- Veuillez suivre le couloir.|- Si vous...
{56839}{56888}Mulder. Arrête.
{56911}{57003}Nous sommes des agents du FBl.|Je vais vous montrer une pièce d'identité.
{57041}{57155}- Nous menons une enquête.|- Veuillez descendre le long du couloir.
{57268}{57317}Niveau 2 à niveau 6.
{57320}{57388}J'ai ici un homme|et une femme qui disent être...
{57391}{57422}Hé! Arrêtez!
{57425}{57475}Arrêtez!
{57598}{57647}Il a pris l'escalier! Allez! Vite!
{57815}{57862}ENTREE lNTERDlTE
{57932}{57956}HAUTE TENSlON
{58324}{58359}Vite! Vite!
{58362}{58405}Ne bougez pas!
{58408}{58467}J'ai dit, ne bougez pas!
{58503}{58552}Ne bougez pas!
{58653}{58715}Relâchez-le.
{58778}{58827}Relâchez-le!
{58830}{58879}Bon travail.
{58882}{58931}Vous pouvez vous retirer.
{59168}{59215}Je sais que vous avez envie...
{59218}{59340}tellement envie de regarder|à travers cette vitre.
{59343}{59410}Mais ça ne servirait à rien.
{59413}{59453}Il est mort.
{59534}{59603}Après l'incident de Roswell en 1947,
{59606}{59665}à l'aube de la guerre froide,
{59668}{59758}il y a eu une conférence|ultra-secrète, entre les Etats-Unis,
{59761}{59841}I'URSS, la Chine Populaire,|la Grande-Bretagne,
{59844}{59893}Ies deux Allemagnes, la France...
{59896}{59945}Et il fut décidé,
{59948}{60059}que si le moindre extraterrestre|devait survivre à un accident,
{60062}{60210}Ie pays qui détiendrait cette chose aurait|la responsabilité de l'exterminer.
{60299}{60346}J'ai...
{60349}{60477}Ia distinction d'être l'une des trois personnes|à avoir exterminé une telle créature.
{60534}{60588}Je travaillais pour la ClA au Viêt-nam.
{60614}{60693}Un OVNl avait été aperçu cinq nuits|de suite au-dessus de Hanoi.
{60696}{60779}Les fusiliers marins l'ont|descendu et nous l'ont amené.
{60857}{60968}Peut-être... qu'il ne savait|pas ce qu'était un pistolet.
{60971}{61036}Ou peut-être qu'ils|ne montrent pas leurs émotions.
{61086}{61143}Mais cette
{61146}{61260}expression innocente et vide|quand j'ai appuyé sur la gâchette
{61263}{61322}m'a longtemps hanté.
{61366}{61407}Jusqu'à ce que je vous trouve.
{61438}{61488}C'est pour ça que je m'adresse à vous,
{61491}{61549}et que je continuerai à m'adresser à vous,
{61554}{61647}pour expier ce que j'ai fait.
{61650}{61707}Et peut-être qu'un jour,
{61710}{61796}à travers vous, la vérité ressortira.
{62317}{62366}ENTREE lNTERDlTE|SECURlTE NlVEAU 6
{62742}{62800}Vous êtes terriblement silencieux, M. Mulder.
{62888}{62952}Je suis en train de|me demander quel mensonge croire.
{64173}{64216}Sous-titres DVD: Visiontext
{64458}{64507}C'est moi qui l'ai fait!
{64541}{64590}FRENCH
