{91}{150}SIEGE SOCIAL D'EURISKO,|CRYSTAL CITY,VIRGINIE
{153}{270}Ben, ça me rend fou. Ne vois-tu pas?|C'est clair comme de l'eau de roche.
{273}{330}Pourquoi|le cours de nos actions chute-t-il?
{333}{398}Parce que tu as divisé en 2|le budget de la recherche!
{401}{462}Tu as perdu le goût de l'aventure.
{465}{543}L'industrie évolue.|Nous devons faire des choix difficiles.
{546}{656}- Garde tes discours pour la presse!|- Ne refaisons pas l'assemblée générale.
{659}{740}Tu es en train de me tuer!|Tu assassines ma société!
{743}{835}Eurisko n'est pas ta société, Brad.|Plus maintenant.
{838}{903}Et tu devrais grandir et t'y habituer!
{906}{961}Tu le regretteras.
{1148}{1192}Nouveau paragraphe.
{1195}{1259}Je suis convaincu|que Ie conseil admettra que
{1262}{1390}Eurisko doit affronter Ia dure réalité|d'un monde de plus en plus compétitif.
{1418}{1498}Depuis Ie départ déplorable|de Brad Wilczek,
{1501}{1647}j'ai fait des propositions visant|à refaire d'Eurisko Ie Ieader du marché.
{1662}{1796}La priorité absolue est de mettre|immédiatement un terme au projet COS.
{1814}{1987}Les terribles résultats du dernier|semestre et Ies pertes prévues pour 1994
{2000}{2061}ne nous Iaissent aucune autre option.
{2870}{2919}Allô. Allô.
{2922}{2997}Au bip, heure normale de I'Est,
{3000}{3039}il sera 19h35.
{3042}{3091}Bon sang, qu'est-ce...?
{3302}{3346}Merde.
{3993}{4047}Fichier supprimé.
{4137}{4204}AUX FRONTIERES DU REEL
{4484}{4555}ACTIVITE PARANORMALE
{4673}{4728}LE GOUVERNEMENT NOUS MENT
{5141}{5200}LA VERITE EST AlLLEURS
{5256}{5336}SIEGE DU FBI, WASHINGTON, D.C.
{5799}{5843}Mulder.
{5861}{5905}Jerry?
{5991}{6065}Vous êtes Dana Scully, n'est-ce pas?|Jerry Lamana.
{6068}{6176}- On était ensemble aux crimes violents.|- J'étais ton coéquipier!
{6198}{6242}8 dollars 50, s'il vous plaît.
{6245}{6344}- Jerry, qu'est-ce qui t'amène?|- Toi. Et je vous offre le déjeuner.
{6347}{6414}- Non, ce n'est pas la peine.|- J'insiste.
{6441}{6480}Voilà.
{6492}{6586}- Mort par électrocution.|- Et ce n'est pas accidentel?
{6589}{6699}Ca ressemble à un piège minutieux,|mais on n'en sait pas vraiment plus.
{6702}{6754}L'ingénieur l'a découvert il y a 12 heures.
{6757}{6851}- Qui mène l'enquête?|- Vous connaissez Nancy Spiller?
{6854}{6916}Le prof de médecine légale|à l'école du FBl!
{6936}{7013}- On l'appelait la dame de fer.|- Dans ses bons jours!
{7016}{7080}Enfin, elle est en train de former l'équipe
{7083}{7145}et je me suis permis de donner ton nom.
{7211}{7314}Jerry,j'aimerais t'aider, mais|on ne traite pas des affaires générales.
{7328}{7377}A cause des affaires non-classées?
{7439}{7568}Ecoute, la vérité, c'est que j'ai besoin|d'aide. Je ne peux pas me planter.
{7571}{7621}Tu ne vas pas te planter.
{7624}{7710}Drake n'était pas que le PDG|d'une société classée au Fortune 500.
{7713}{7779}Il était l'ami du procureur général.
{7782}{7885}J'aurais vraiment besoin|d'un coup de pouce sur cette affaire.
{7888}{7947}- Ouais, mais, Jerry...|- Ecoute,
{7952}{8021}Je ne te le demanderais pas|si ce n'était pas important.
{8063}{8165}- Pourquoi n'êtes-vous plus équipiers?|- C'est pénible de travailler avec moi.
{8168}{8237}- Sérieusement, Mulder.|- C'est pas pénible?
{8240}{8295}Objectifs de carrière différents.
{8298}{8347}Jerry visait le bureau du directeur.
{8350}{8420}- Et toi?|- Moi, plutôt un bureau au sous-sol
{8423}{8467}sans chauffage ni fenêtre.
{8470}{8544}Bon, je sais où tu as abouti.|Et Jerry?
{8547}{8631}Il a eu un contretemps à la brigade|des crimes de haine à Atlanta.
{8634}{8717}- Quel genre de contretemps?|- ll a égaré une pièce à conviction.
{8720}{8769}Il l'a envoyée au pressing.
{8772}{8864}Entre-temps, un juge fédéral|avait perdu deux mains et un oeil.
{9046}{9092}29?
{9136}{9214}- L'ascenseur monte.|- Certainement pour les malvoyants.
{9217}{9285}Ca alors!|Un ascenseur politiquement correct.
{9288}{9337}Troisième étage.
{9355}{9399}Quatrième étage.
{9411}{9481}- Ca va?|- Ouais.
{9492}{9541}Qu'est-ce qui s'est passé?
{9721}{9765}- Oui?|- Allô?
{9768}{9841}- Sécurité. Qui est-ce?|- Je suis l'agent Dana Scully.
{9844}{9916}- Avez-vous un problème?|- Cinquième étage. Sixième étage.
{9934}{9988}En fait, tout est rentré dans l'ordre.
{9991}{10077}Neuvième étage.|Dixième étage. Onzième étage.
{10133}{10217}DlSTRlCT OF COLUMBlA|RECHERCHE TELEPHONlQUE
{10322}{10390}Vous voyez là?|Quelqu'un a trafiqué le servo.
{10393}{10453}Ils ont mis la terre sur négatif,
{10456}{10548}- et quand il a mis la clé dans la porte...|- ll a complété le circuit.
{10551}{10640}Ca a fondu. Faut un sacré jus|pour faire fondre une clé en acier.
{10643}{10717}Et pour envoyer un homme|de 90 kilos à trois mètres.
{10733}{10814}L'interrupteur du servo -|peut-on le déplacer manuellement?
{10817}{10888}Nous n'avons trouvé aucune empreinte.
{10891}{11012}Oui. Il aurait pu être trafiqué, mais|la personne aurait dû neutraliser le COS.
{11015}{11077}- C'est quoi le COS?|- Système d'exploitation central.
{11080}{11119}Il fait tourner l'immeuble.
{11122}{11241}Il régule tout, de l'énergie au volume|d'eau dans chaque chasse d'eau.
{11244}{11344}Claude Peterson, ingénieur-système|de l'immeuble. Il a découvert le corps.
{11347}{11417}Si on voulait neutraliser le COS,|que faudrait-il...?
{11420}{11542}D'abord briser le code d'accès,|ce qui... n'est pas une mince affaire.
{11545}{11620}Il nous faut la liste|des personnes qui en sont capables.
{11623}{11693}Je vous préviens d'une chose,|la liste sera courte.
{11696}{11774}- Seriez-vous dessus?|- Moi?!
{11777}{11870}Hé, attendez, je ne suis|qu'un gérant d'immeuble glorifié.
{11873}{11965}Je contrôle le système et|m'assure qu'il fonctionne correctement,
{11968}{12040}j'ai ainsi remarqué|la surcharge dans le bureau de M. Drake.
{12043}{12123}Et les lignes téléphoniques?|Le COS contrôle les appels?
{12126}{12222}- Oui. Pourquoi?|- Juste une question.
{12243}{12292}OK. Je peux y aller maintenant?
{12404}{12457}Pourquoi les lignes téléphoniques?
{12481}{12530}Le combiné est décroché.
{12606}{12743}Drake parlait peut-être à quelqu'un|avant de jouer les Benjamin Franklin.
{12760}{12809}Je lui ai tout appris.
{12921}{12982}SlEGE DU FBl, WASHlNGTON, D.C.
{13008}{13047}Entrez.
{13060}{13099}Il est trois heures passées.
{13102}{13176}Je cherche mes notes sur le profil.
{13179}{13255}Peut-être que si tu rangeais|ton bureau plus souvent.
{13258}{13317}Je les ai posées ici, je t'assure.
{13386}{13414}On est en retard.
{13633}{13709}Nous devons considérer deux points.
{13712}{13835}La faible occurrence|de meurtres par électrocution
{13838}{13957}et la complexité du crime indiquent|une certaine préméditation tortueuse.
{13978}{14062}Après tout, il y a des façons|bien plus simples de tuer quelqu'un.
{14135}{14258}Ce qui nous laisse à penser que l'auteur|du crime est un joueur sociopathe
{14261}{14305}peut-être même un reclus,
{14308}{14385}il a en effet conçu un piège|pour éviter toute détection,
{14388}{14450}et pour éviter tout contact avec la victime.
{14486}{14530}Est-ce que c'est ton profil?
{14533}{14578}Laisse tomber. Non.
{14581}{14661}Le dernier appel pris par Drake|vient étayer cette théorie.
{14683}{14791}Au bip, heure normale de I'Est,|il sera 19h35.
{14794}{14844}L'heure estimée du décès de Drake.
{14847}{14923}Pourquoi Drake voulait-il|savoir l'heure avant de mourir?
{14926}{14975}C'était un appel entrant
{14978}{15044}provenant de l'immeuble Eurisko même.
{15047}{15138}Celui qui a posé ce piège voulait|être sûr que Drake morde à l'hameçon.
{15187}{15271}- Excellent travail, agent Lamana.|- Merci.
{15461}{15514}Jerry, qu'est-ce que tu fous?
{15517}{15599}- Hé, t'excite pas.|- C'était mon profil.
{15602}{15659}J'ai pensé que ça ne te dérangerait pas.
{15724}{15799}Ce n'était que des notes.|Le reste est de moi.
{15802}{15883}Jerry, tu es entré dans mon bureau|et tu as volé mon travail.
{15886}{15998}Tu es sur ce cas car je t'ai demandé|de m'aider et tu m'as aidé, c'est tout.
{16001}{16050}Pourquoi fais-tu des histoires?
{16182}{16283}- Qu'est-ce qu'il a dit?|- ll s'est excusé... à sa manière.
{16324}{16418}Je viens de parler à Peterson,|l'ingénieur-système.
{16421}{16473}Un seul nom! Brad Wilczek?
{16476}{16525}Il avait dit que la liste serait courte.
{16528}{16592}Et tout le monde sait|combien il méprisait Drake.
{16594}{16700}Ca semble trop évident. Tuer Drake|ne serait qu'un acte égocentrique éhonté.
{16703}{16807}Et coinciderait tout à fait|avec le profil de comportement de Jerry.
{16813}{16865}Tout à fait.
{17404}{17527}Voici le résultat d'un Ql de 220|et d'indemnités de départ de 400 millions.
{17780}{17814}Oui?
{17840}{17916}Brad Wilczek? FBl.
{17935}{17984}Il vous en a fallu du temps!
{18076}{18133}Enlevez vos chaussures, s'il vous plaît.
{18193}{18335}L'informatique se divise en deux types|de gens: les soigneux et les désordonnés.
{18338}{18448}- Benjamin Drake était du premier type?|- Ces gens aiment les choses soignées.
{18451}{18535}Leurs costumes sont nickels|et ils s'intéressent au concret.
{18538}{18646}A ce qu'ils comprennent: le cours|des actions et les profits trimestriels.
{18649}{18721}Et vous envisagez|la société différemment?
{18724}{18818}J'ai lancé Eurisko dans le garage|de mes parents. J'avais 22 ans.
{18821}{18907}Je venais de passer un an|à suivre les Grateful Dead.
{18910}{18968}Vous savez ce qu'Eurisko signifie?
{18971}{19020}Ca vient du grec, n'est-ce pas?
{19050}{19084}"J'apprends les choses".
{19087}{19148}Cela signifie en fait|"Je découvre les choses".
{19151}{19215}Mais Ben Drake se moquait|de la découverte.
{19218}{19305}C'était un opportuniste|avide de pouvoir et peu clairvoyant.
{19349}{19421}Je vais vous montrer un truc.|La maison intelligente.
{19424}{19510}Avec ce prototype, je peux|accéder à chaque cm² de la maison.
{19513}{19626}Cet endroit est aussi sûr que Fort Knox|et aussi éco-énergétique qu'un igloo.
{19629}{19689}Nous avions deux ans|d'avance sur Microsoft
{19692}{19788}Iorsque Drake, dans sa sagesse infinie,|a mis fin au programme.
{19791}{19869}Ce système a-t-il un lien|avec celui de l'immeuble de la société?
{19872}{19907}Variation sur le même thème.
{19910}{19999}Combien de personnes connaissent|assez le système pour le neutraliser?
{20002}{20101}Enfin la question bonus.|Je vous répondrai: pas beaucoup.
{20126}{20204}Quelqu'un aurait-il pu|s'introduire dans le système?
{20207}{20282}Pas le pirate lambda, c'est sûr.
{20285}{20422}Il y a des dingues! Voleurs de données,|as de l'électro, techno-anarchistes.
{20425}{20474}Tout est possible.
{20477}{20592}- Vous pourriez l'avoir fait?|- Bien sûr. J'ai conçu le système.
{20625}{20682}C'est pour ça que vous êtes ici, hein?
{20685}{20734}Je suis votre suspect désigné.
{20749}{20802}Vous n'avez pas l'air trop inquiet.
{20805}{20866}C'est une énigme, Mlle Scully.
{20869}{20944}Les esprits désordonnés|comme le mien aiment les énigmes.
{20947}{21069}Nous aimons explorer des voies|de l'esprit nouvelles et imprévisibles.
{21072}{21174}Mais, en règle générale, un esprit|désordonné ne commet pas de meurtre.
{21323}{21411}Le génie serait d'établir des Iiens|entre des choses qui n'en ont pas.
{21414}{21518}Faire des juxtapositions. Voir des Iiens|invisibles aux yeux des autres.
{21521}{21575}Brad Wilczek est-il un génie?
{21579}{21628}Je ne sais pas.
{21631}{21680}Mais je sais une chose.
{21683}{21753}II a une prédilection|pour Ies jeux éIaborés
{21756}{21811}et il connaît I'immeuble Eurisko.
{21814}{21908}En plus, il a un motif évident|pour assassiner Benjamin Drake.
{21922}{21971}La question continue de se poser.
{21987}{22056}Mais s 'il est si intelligent,|comment Ie coincer?
{22093}{22178}Fin du journal de terrain, 24 octobre 1993.
{23224}{23292}BALAYAGE COS: SCULLY, DANA -|lNTERCEPTlON DE DONNEES
{23419}{23468}Fichier ouvert.
{23623}{23717}Dès Ie début, j'ai su qu'Eurisko|se développerait bien,
{23720}{23827}pas sur Ies bases traditionnelles|occidentales, mais certains concepts Zen
{23830}{23885}et d'autres philosophies orientales.
{23933}{23988}Et d'autres philosophies orientales.
{24036}{24085}Philosophies orientales.
{24119}{24168}Philosophies...
{24298}{24347}Tu m'excuses une seconde?
{24472}{24529}Ecoute, je viens|te présenter mes excuses.
{24532}{24600}J'ai merdé.|Je suis désolé. Que dire d'autre?
{24603}{24706}Tu n'avais qu'à me demander.|Je t'aurais aidé à rédiger le profil.
{24738}{24812}- Tu ne sais pas ce que c'est.|- Quoi?
{24815}{24854}Tu as su pour Atlanta?
{24857}{24977}J'ai une période d'essai de six mois. Je|dois faire des rapports comme un novice.
{24980}{25044}Tu n'as pas eu de pot.|Ca pourrait tous nous arriver.
{25073}{25123}Pas à toi.
{25163}{25227}Ne te rabaisse pas. Tu es un bon agent.
{25229}{25334}- On a bien travaillé ensemble.|- Franchement, j'étais à la traîne.
{25337}{25389}- Ce n'est pas vrai.|- Comment le saurais-tu?
{25392}{25468}Tu étais trop occupé à les éblouir là-haut.
{25471}{25515}Mulder.
{25518}{25567}Regarde ça.
{25716}{25807}Nous avons emprunté ça au labo|de biométrie vocale à Georgetown.
{25810}{25931}C'est un spectrographe synthétique|identifiant des modèles linguistiques.
{25934}{26067}Voici l'enregistrement du COS|de l'appel reçu par Drake avant sa mort.
{26127}{26223}Au bip, heure normale de I'Est,|il sera 19h35.
{26260}{26392}Ceci provient de conférences données|par Wilczek l'an dernier au Smithsonian.
{26429}{26532}Au bip, heure normale de I'Est,|il sera 19h35.
{26551}{26600}Puis nous les superposons.
{26654}{26768}Au bip, heure normale de I'Est,|il sera 19h35.
{26785}{26894}- Selon vous, c'est la même personne?|- Les deux voix sont à Brad Wilczek.
{26897}{27020}Sa voix a été changée, pas les formats|uniques à son modèle linguistique.
{27023}{27096}Ce qui veut dire qu'il a bien tué Drake.
{27099}{27160}Il avait un mobile|et les moyens de le tuer.
{27163}{27228}Et maintenant,|nous en avons la preuve physique.
{27231}{27292}RECHERCHE: CORRESPONDANCE
{27313}{27420}Le juge Benson vit à Washington Heights.|J'aurai un mandat en moins d'une heure.
{27423}{27477}Wilczek ne doit pas s'envoler.
{27480}{27564}- Je vais avec toi.|- Non, je veux l'épingler seul.
{27567}{27606}Accorde-moi celui-là, Mulder.
{27634}{27668}D'accord.
{28017}{28076}Allez, bon sang. Laisse-moi entrer.
{28323}{28372}ACCES REFUSE
{28474}{28496}Merde!
{28499}{28550}ACCES REFUSE
{29401}{29450}M. Wilczek!
{29524}{29577}L'ascenseur monte.
{29580}{29650}Deuxième étage.|Troisième étage. Quatrième...
{29881}{29947}- Puis-je vous aider?|- FBl.
{30366}{30411}ACCES AU SYSTEME AUTORlSE
{30414}{30457}Heureux de te revoir, Brad.
{30535}{30603}Tu n'es pas doté|d'un système de synthèse de la parole.
{30666}{30722}Quel est mon niveau d'accès?
{30725}{30796}Ceci est maintenant|à Ia discrétion du système.
{31014}{31053}L 'ascenseur monte.
{31056}{31126}2e étage. 3e étage. 4e étage.
{31129}{31274}5e étage. 6e étage.|7e étage. 8e étage. 9e étage.
{31277}{31407}10e étage. 11e étage.|12e étage. 14e étage.
{31410}{31490}15e étage. 16e étage.
{31493}{31542}Mais qu'est-ce...?
{31545}{31584}Qu'est-ce que tu fais?
{31587}{31691}Désolé. Ces commandes ne sont|pas disponibles à ce niveau d'accès.
{31694}{31733}Essaie de nouveau.
{31742}{31810}21e étage. 24e étage.
{31841}{31924}- Qu'est-ce que tu fais?!|- Qu'est-ce que tu fais?
{32013}{32110}28e étage. 29e étage.
{32113}{32152}30e étage.
{32155}{32287}29e. 30e.|29e. 30e...
{32290}{32379}29e. 30e...|29e. 30e...
{32693}{32742}Oh, mince!
{32807}{32856}L 'ascenseur descend.
{32928}{33002}Non! Ne fais pas ça!
{33186}{33242}Oh, mon Dieu.
{33403}{33452}Programme exécuté.
{34657}{34706}J'ai appris pour Jerry.
{34740}{34789}Je suis désolée.
{34834}{34883}Je ne pense pas que Wilczek l'ait fait.
{34932}{34976}Quoi?
{34989}{35038}Ca n'a pas de sens.
{35041}{35090}Pourquoi retournerait-il à Eurisko?
{35125}{35189}Pour détruire des preuves.|Pour effacer toute trace.
{35192}{35282}Si tu devais détruire des preuves,|poserais-tu devant les caméras?
{35588}{35637}Mulder.
{35674}{35723}Beaucoup de choses viennent de t'arriver.
{35729}{35786}Plus que tu ne le réalises toi-même.
{35873}{35930}Je pense que Wilczek est plus fin que ça.
{36121}{36170}Il vient de signer des aveux.
{36237}{36286}Quelle autre preuve veux-tu?
{36862}{36922}Vous êtes sur les lieux d'un crime. Partez.
{36925}{36981}Ouais, je sais. J'ai demandé le mandat.
{36984}{37073}- Ce mandat n'a pas été éxécuté.|- De quoi parlez-vous?
{37076}{37201}A moins que vous n'ayez une autorisation|code 5, vous allez devoir partir d'ici.
{37854}{37940}- Merci d'être venu.|- Je sais que je fais une erreur.
{37943}{38056}A l'avenir, vous devrez respecter|les termes de notre accord.
{38059}{38203}Pourquoi Wilczek est-il Code 5?|Que lui veut le ministère de la Défense?
{38206}{38324}Pourquoi vouloir le programmeur|le plus novateur de cet hémisphère?
{38327}{38375}- Logiciel?|- Bingo.
{38378}{38513}Depuis des années, Wilczek fait la nique|à tout contrat lié à l'armement.
{38516}{38564}C'est un coeur sensible.
{38567}{38616}Quelle sorte de logiciel?
{38619}{38706}Que savez-vous|de l'intelligence artificielle?
{38709}{38766}Je croyais|que ce n'était que théorique.
{38769}{38818}Ca l'était... jusqu'à il y a deux ans.
{38821}{38921}Helsinki. Echecs. Première victoire|d'un ordinateur sur un grand maître.
{38924}{38970}C'était le programme de Wilczek.
{38995}{39099}Et, selon la rumeur, il l'avait conçu en|développant le premier réseau adaptatif.
{39102}{39155}Un réseau adaptatif?
{39158}{39222}C'est une machine érudite.
{39225}{39285}Un ordinateur qui pense.
{39304}{39400}Et c'est... devenu le Saint Graal
{39403}{39504}pour certains de nos collègues les plus|curieux du ministère de la Défense.
{39578}{39601}CENTRE DE DETENTlON FEDERAL
{39604}{39695}Ils me font porter ces chaussures|tout le temps. Que voulez-vous d'autre?
{39698}{39812}Pourquoi passer le reste de votre vie|en prison alors que vous êtes innocent?
{39815}{39922}- N'importe quoi! Je suis coupable!|- Je sais que vous êtes innocent!
{39934}{40049}Vous protégez la machine. Le système|d'exploitation central à Eurisko.
{40078}{40152}Si je protège quoi que ce soit,|ce n'est pas la machine.
{40193}{40242}Alors quoi?
{40335}{40438}Après l'explosion de la bombe|à Hiroshima et Nagasaki,
{40458}{40586}Robert Oppenheimer a regretté toute|sa vie d'avoir même entrevu un atome.
{40588}{40708}Si Oppenheimer a regretté ses actes,|il en a toujours assumé la responsabilité.
{40711}{40780}Il adorait son travail, M. Mulder.
{40826}{40915}Son erreur a été de le partager|avec un gouvernement immoral.
{40937}{40986}Je ne ferai pas la même erreur.
{41004}{41063}Mais votre machine a tué Drake.
{41085}{41124}Ainsi que mon ami.
{41190}{41243}Je suis désolé de ce qui s'est passé,
{41246}{41300}mais je ne peux rien y faire.
{41303}{41350}Et vous parlez de moralité!
{41353}{41467}Vous craignez ce gouvernement, mais|vous acceptez que la machine tue encore.
{41470}{41526}Entre deux maux,|il faut choisir le moindre.
{41563}{41612}Et s'il y avait une troisième solution?
{41680}{41734}Vous avez créé la machine.
{41737}{41793}Dites-moi comment la détruire.
{41876}{41943}Wilczek peut créer un virus|qui détruira le système.
{41946}{42040}Mulder, incriminer la machine|est un alibi, mauvais en plus.
{42043}{42093}C'est la seule option qui ait du sens.
{42096}{42160}Eurisko perdait une fortune|avec le projet COS.
{42163}{42212}Drake allait arrêter le programme.
{42215}{42287}Et la machine a tué Drake|dans un acte de légitime défense?
{42290}{42376}De survie - l'instinct primaire|de tout être doté de sensations.
{42379}{42500}Mulder, on est à des décennies|de ce niveau d'intelligence artificielle.
{42503}{42603}Pourquoi le gouvernement essaie-t-il|d'usurper la recherche de Wilczek?
{42623}{42697}Je crois que tu cherches|quelque chose qui n'existe pas.
{42700}{42766}Et je crois|que ça a un rapport avec Jerry.
{42803}{42907}Tu devrais peut-être parler à quelqu'un.
{42976}{43025}Tu as probablement raison.
{43071}{43140}- Où vas-tu?|- Parler à quelqu'un.
{43723}{43777}De combien de temps avez-vous besoin?
{44395}{44429}Allô?
{44797}{44846}Oh mon Dieu.
{44993}{45122}Agent spécial Dana Scully,|numéro d'identification 2317-616.
{45125}{45209}Je voudrais que vous établissiez|l'origine d'un numéro. Ouais.
{45228}{45295}202-555-6431.
{45298}{45396}Oui, c'est mon numéro. Quelqu'un|est en train d'accéder à mon ordinateur.
{46001}{46069}- Mulder!|- Scully, que fais-tu ici?
{46072}{46176}Quelqu'un ou quelque chose a balayé|mon ordi, mis mon téléphone sur écoute.
{46179}{46270}J'ai établi l'origine. Ca venait d'ici.
{46317}{46366}C'est la machine.
{46441}{46485}Comment peut-on entrer?
{46574}{46623}Tu te souviens du cheval de Troie?
{46645}{46691}ACCES REFUSE
{46897}{46924}PASSER
{46969}{47034}Ouvre-toi Sésame.
{47310}{47344}Oh, qu'est-ce...
{47359}{47408}Mulder!
{47815}{47870}Ca, c'est un effet de surprise!
{47917}{47968}Et si on prenait les escaliers?
{48264}{48321}28 étages montés, encore un.
{48447}{48491}Oh, génial.
{48494}{48533}Mulder?
{48696}{48745}Piège ou petit plaisir?
{48944}{48983}Non!
{48986}{49083}- Qu'est-ce que tu fais?|- Ne refaisons pas l'erreur de Drake.
{50232}{50276}Qui regardes-tu?
{50887}{50976}Tu devrais pouvoir ouvrir la porte.
{52161}{52205}Allez, Scully.
{52630}{52674}Scully?
{52763}{52832}Agent Mulder. Que faites-vous ici?
{54794}{54900}La machine n'a pas arrêté de délirer.|Saute de puissance, arrêt soudain.
{54903}{54952}C'est pour ça que je suis là si tard.
{54963}{55035}- Où est le port B?|- Oh, c'est là, derrière.
{55272}{55402}Vous êtes sûr de savoir ce que vous|faites? Sinon, mon boulot est en jeu.
{55542}{55581}ACCES REFUSE
{56514}{56568}Accès système accordé.
{56586}{56635}Code utilisateur:. niveau 7.
{56640}{56689}Maintenant, je peux insérer le virus.
{56712}{56761}Pas mal, agent Mulder.
{56764}{56869}Vous savez, ça fait deux ans|que j'essaie d'accéder à l'unité centrale.
{56872}{56957}Prenez votre arme|et retirez votre chargeur, s'il vous plaît.
{57096}{57140}Attention.
{57243}{57282}Ministère de la Défense?
{57285}{57355}Disons que la même personne|signe nos chèques de paie.
{57358}{57426}Donnez-moi la disquette et éloignez-vous.
{57519}{57611}Ne mettez pas ma détermination|à l'épreuve, agent Mulder.
{57741}{57790}Posez ce flingue.
{57853}{57948}- Vous ne savez pas ce que vous faites.|- Fermez-la et jetez le flingue!
{58078}{58138}Vous faites une grosse erreur,|agent Scully.
{58241}{58296}Compromettant vos obligations.
{58299}{58390}Cette opération est plus délicate|que vous ne l'imaginez.
{58393}{58477}- Ne l'écoute pas.|- La technologie de cette machine
{58480}{58532}a un intérêt scientifique phénoménal.
{58535}{58603}C'est un monstre.|Elle a tué deux personnes.
{58606}{58695}- Même Wilczek ne peut plus la manier.|- Ne faites pas d'erreur.
{58698}{58760}Vous serez tenue responsable.
{58839}{58883}Mulder, insère la disquette.
{58982}{59031}Qu'est-ce que tu fais, Brad?
{59041}{59090}Ne fais pas ça, Brad.
{59103}{59224}Commande ou nom de fichier incorrect.|Impossible de trouver Secteur 7.
{59999}{60043}Brad...
{60055}{60104}Brad...
{60129}{60195}Brad... pourquoi?
{60798}{60886}J'ai vérifié|avec les Services correctionnels.
{60889}{60989}- J'ai contacté le procureur général.|- Vous ne le trouverez pas.
{60992}{61078}Ils ne peuvent pas enlever|Brad Wilczek sans aucune explication.
{61081}{61165}Ils peuvent faire|ce que bon leur semble.
{61189}{61235}Où est-il?
{61256}{61336}En "négociation intensive",|comme on dit dans le métier.
{61359}{61431}Wilczek ne traitera pas.|Il ne travaillera jamais pour eux.
{61434}{61549}L'absence de liberté pousse à bien des|choses, et il a confessé deux meurtres.
{61552}{61665}De plus, vous venez de détruire|la seule preuve qui pouvait le disculper.
{61703}{61753}Qu'aurais-je pu faire d'autre?
{61775}{61890}Rien, à moins que vous ne laissiez|la technologie vivre.
{61925}{62001}Le ministère de la Défense|n'a toujours rien trouvé?
{62028}{62124}Ils planchent dessus depuis cinq jours.|Le virus de Wilczek était efficace.
{62127}{62209}Aucune trace|de l'intelligence artificielle ne demeure.
{62235}{62284}La machine est morte.
{62626}{62717}Nous avons poussé au maximum|les modulations par impulsions codées.
{62720}{62769}Rien.
{62848}{62921}Nous avons passé au peigne fin|le sous-programme d'analyse.
{62924}{62973}Oui. Deux fois.
{62976}{63053}Non. Toujours rien,|mais je souhaite demander...
{63178}{63212}Oui.
{63215}{63264}Non, je comprends.
{63267}{63311}Oui.
{63337}{63493}On a six heures avant d'envoyer|ce merdier au déchiqueteur de métal.
{63496}{63547}Nous faisons de notre mieux.
{64132}{64216}Je vais trouver comment marche ce truc|même si je dois y Iaisser ma peau.
{64308}{64413}Sous-titrage Visiontext: Claire ltani
{65066}{65105}C'est moi qui I'ai fait!
{65128}{65177}FRENCH
