{84}{167}TOWNSEND, WISCONSIN|00H57 1ER JOUR
{438}{553}Incendie sur la départementale D7, 3 km|à l'ouest du croisement de Canyon Ridge.
{556}{613}Envoyez les pompiers. A vous.
{670}{734}Ici le shérif adjoint Wright. Reçu?
{780}{829}Fils de...
{1303}{1394}Désolé de vous déranger colonel,|on a détecté un objet non-identifié.
{1397}{1462}Je crois que vous devriez voir la séquence.
{1749}{1842}Il a franchi la barrière|à 23H17 au large du Connecticut.
{1845}{1923}Trajectoire nord-nord-ouest,|puis complètement folle.
{1926}{2040}- Un autre avion ou des essais de missiles?|- Aucun avion connu ne peut faire ça.
{2089}{2160}En tout cas,|il a disparu de l'écran en zone 24.18.
{2163}{2250}Il a atterri à l'ouest du lac Michigan,|à Townsend, Wisconsin.
{2253}{2345}L'équipe de prédiction d'impact|a calculé un choc à plus de 1200 km/h.
{2379}{2431}J'ai demandé un rapport à Koretz.
{2434}{2481}- Avec ces cassettes pour...|- Non.
{2523}{2626}C'est un météore. Ce mouvement anormal|vient d'une défaillance du radar.
{2629}{2719}- Mais...|- C'est ce que dira votre rapport. C'est clair?
{2722}{2771}Oui, mon colonel.
{2793}{2837}Bien.
{3029}{3095}Code lndigo Delta Echo Neuf.
{3098}{3184}Confirmation d'un ange déchu|dans le secteur 87.
{3187}{3274}Lancez immédiatement l'Opération Faucon.
{3677}{3724}Il y a quelqu'un?
{4321}{4387}AUX FRONTIERES DU REEL
{4671}{4744}ACTIVITE PARANORMALE
{4857}{4922}LE GOUVERNEMENT NOUS MENT
{5327}{5387}LA VERITE EST AILLEURS
{5444}{5576}Aucun commentaire|jusqu'à la fin de l'enquête du gouvernement.
{5579}{5666}Le gouvernement reste vague|quant au chargement toxique
{5669}{5801}qui a causé I'évacuation des 12000 habitants|de Townsend, Wisconsin.
{5804}{5894}On pense qu'il s'agirait|d'une cargaison de déchets toxiques.
{5897}{5971}Alors qu'est-il arrivé|si aucun train n'a déraillé?
{5974}{6093}M. Mulder, les Etats-Unis|sont entourés d'une barrière électronique
{6096}{6185}qui atteint 24000 km de haut dans l'espace.
{6204}{6374}Elle sert à suivre et contrôler|les 7087 objets en orbite autour de la Terre.
{6377}{6475}Hier soir à 23H17, cette barrière a été franchie.
{6478}{6595}Ce matin à 01H00,|l'Opération Faucon a commencé,
{6598}{6720}menée par le colonel Henderson,|expert en recouvrement de l'armée de l'air.
{6723}{6759}Recouvrement?
{6762}{6877}Pendant la Guerre Froide, il évitait|que la technologie de nos avions écrasés
{6880}{6934}ne tombe aux mains des Russes.
{6937}{7003}Il fait... partie d'une unité de récupération?
{7058}{7113}Réaction rapide.
{7116}{7212}Je dirais que vous avez... 24 heures
{7215}{7269}avant que la zone ne soit désinfectée.
{7272}{7311}Après cela,
{7314}{7379}ce sera comme si rien ne s'était passé.
{8487}{8544}Allez! Allez!
{8576}{8625}Magnez-vous!
{9094}{9143}- Merci, chef.|- Merci.
{9146}{9200}On se bouge. Allez! Allez!
{9287}{9371}- Bon, on dégage!|- Les barrages routiers doivent être en place.
{9374}{9433}Reçu. Je m'en occupe tout de suite, chef.
{9436}{9485}QUARTlER GENERAL,|OPERATlON FAUCON
{9698}{9796}- ll est tard. La nuit va tomber.|- On a crevé.
{9799}{9898}Briefing à 22H00. Passez d'abord au QG,|prendre des balles réelles.
{9901}{9935}Des balles réelles?
{9938}{10023}- Un problème?|- Non! On nous a dit que c'était un exercice.
{10026}{10075}- On vous a mal informé.|- Mon colonel.
{10138}{10212}OK, tout le monde dehors!|Allez! Remuez-vous!
{14132}{14231}Vous avez commis|la pire erreur de votre vie, agent Mulder.
{14293}{14342}Vous avez gâché une pellicule.
{14345}{14417}Vous allez payer|pour avoir mis mes hommes en danger.
{14420}{14502}Depuis quand prendre des photos|met des vies en danger?
{14505}{14605}Vous avez violé une zone de quarantaine|du gouvernement, c'est un crime.
{14608}{14672}Une quarantaine?|Vous appelez ça comme ça?
{14674}{14760}Nous essayons|de contenir un désastre écologique.
{14763}{14836}Ca fait beaucoup d'armes à feu|pour protéger Mère Nature.
{14875}{14924}J'ai mes ordres.
{14927}{14994}Et je peux les exécuter|comme bon me semble.
{14997}{15107}Je vous suggère|d'oublier ce que vous avez cru voir,
{15110}{15159}dans votre propre intérêt.
{15162}{15290}Il y a un avion écrasé dans cette forêt,|et des troupes armées de balles réelles.
{15293}{15347}Nous savons tous deux ce qui est là-bas!
{15441}{15520}- Allez, remuez-vous.|- C'est ça, mon gars.
{15543}{15592}Entrez là-dedans.
{15802}{15869}Vous êtes du MOVNl ou du COVNl?
{16023}{16072}Vous permettez que je m'assoies?
{16082}{16165}Laissez-moi deviner.|Vous êtes du nouveau groupe. CSlCOP?
{16241}{16334}Ne dites rien. Un homme prudent.|Confiance en personne - très sage.
{16342}{16425}Après l'affaire Kennedy,je comprends.
{16428}{16475}Permettez-moi de me présenter.
{16478}{16602}Max Fenig. Je suis du Comité national|d'enquête sur les phénomènes aériens.
{16629}{16668}NlCAP.
{16711}{16790}Enchanté... enchanté|de faire votre connaissance.
{16818}{16890}J'aimerais qu'on se serre la main.
{16893}{16982}Poignée ferme. Droit dans les yeux.|Ca en dit long sur un type.
{17051}{17127}Puis-je... Puis-je vous poser une question?
{17160}{17194}Allez-y.
{17197}{17266}Avez-vous vu quelque chose?|Avez-vous pu approcher?
{17269}{17331}Je n'ai rien vu. Rien vu du tout!
{17353}{17481}Zéro. Ils m'ont eu 150 m après les barrages.|Je me demande comment.
{17484}{17577}Je vous le dis,|c'est comme l'affaire Roswell.
{17580}{17663}Pourquoi croyez-vous|qu'il y a quelque chose là-bas?
{17747}{17812}Pour la même raison que vous.
{18551}{18602}Je n'ai pas appelé le service d'étage.
{18605}{18654}Ce n'est pas drôle, Mulder.
{18657}{18711}- Tu connais Max?|- Qui?
{18714}{18763}Max du NlCAP.
{18784}{18833}Ils ont dû le relâcher.
{18836}{18907}Un intrépide en quête|de rencontres du 3ème type.
{18910}{18950}C'est ce dont il s'agit?
{18965}{19014}De quoi d'autre?
{19017}{19083}Explique-le|au chef de section McGrath.
{19086}{19184}Il a ignoré Blevins|et veut une enquête avec recommandation...
{19187}{19280}Il veut fermer les affaires non-classées|et te virer, Mulder.
{19283}{19333}Quoi de neuf?
{19336}{19392}Je ne te comprends pas, Mulder!
{19395}{19454}Pourquoi toujours ignorer le protocole,
{19457}{19508}violer les règles de compétence.
{19511}{19560}Parce que je sais ce que j'ai vu.
{19563}{19656}Comment peut-avoir un déraillement|sans rails?
{19659}{19703}Parce que ça n'en était pas un.
{19706}{19765}Ce que tu as vu|n'était pas une fuite toxique.
{19768}{19817}Ca n'était pas non plus un OVNl.
{19863}{19912}OK, je t'écoute. C'était quoi?
{19915}{19999}Un avion libyen|transportant une ogive nucléaire.
{20048}{20103}Dans l'espace aérien américain?
{20106}{20234}Ils ont détecté des radiations, suggérant|une fissure du container de plutonium.
{20237}{20280}Et pour éviter la panique...
{20283}{20393}- Tu crois vraiment à cette histoire?|- Elle est classée top-secret.
{20396}{20452}Un mensonge top-secret.
{20528}{20632}- lls recherchent quelqu'un, Scully.|- Sûrement le pilote.
{20635}{20727}Tu crois qu'ils déploieraient|tout ce matériel pour un pilote libyen?
{20785}{20867}Et aucun pilote humain|n'a quitté l'épave que j'ai vue.
{20909}{20958}Peut-être qu'il s'est éjecté.
{21000}{21044}Peut-être.
{22079}{22128}Tu n'es pas sérieux.
{22131}{22204}Puisque nous sommes à Townsend,|pourquoi pas?
{22207}{22316}- L'audience est à 10H00 demain matin.|- Ca nous laisse 24 heures pour enquêter.
{22319}{22399}Ma mission est de te ramener,|pas de t'enfoncer davantage.
{22402}{22461}Le Dernier Détail, avec Dana Scully.
{22703}{22750}Que se passe-t-il?
{22753}{22825}On dirait|que la bonne n'est pas encore passée.
{22828}{22857}Qu'est-ce...
{23483}{23527}Max?
{23572}{23621}Les mains en l'air!
{23624}{23678}- Ne tirez pas! Ne tirez pas!|- Max?
{23813}{23865}Mes excuses. Pardonnez-moi.
{23868}{23932}Je-je-je suis curieux.|Il fallait que je sache.
{23934}{23983}- Quoi?|- Si c'était bien vous.
{23986}{24061}Vous ne me connaissez pas.|On s'est rencontré hier.
{24064}{24194}Pas vrai. Le CNEPA a suivi|votre carrière aux affaires non-classées.
{24197}{24281}- Comment?|- Grâce à la loi sur la liberté d'information.
{24284}{24350}Vos frais de transport sont d'intérêt public.
{24395}{24486}Et, ce doit être...|I'énigmatique agent Scully.
{24543}{24650}- Comment m'avez-vous reconnu?|- J'ai vu une photo dans une publication,
{24653}{24749}et j'ai lu votre article dans Omni|sur les apparitions de Golf Breeze.
{24784}{24863}- J'avais utilisé un pseudonyme.|- M.F. Luder. Je sais.
{24866}{24931}M.F. Luder est une anagramme de F. Mulder.
{24934}{25012}Vous ne pensiez pas nous berner, si?
{25015}{25088}Je ne pensais pas|que quelqu'un y ferait attention.
{25091}{25166}Quelqu'un fait toujours attention, M. Mulder.
{25169}{25221}Etonnant.
{25224}{25282}Etonnant? Très peu!
{25285}{25372}Si vous voulez voir|quelque chose d'étonnant, suivez-moi.
{25406}{25468}"L'énigmatique docteur Scully."'
{25752}{25816}Ca c'est mon... Par ici.
{25837}{25878}Excusez le désordre.
{25881}{25955}OK. Où sont ces...
{26062}{26124}Je vais éteindre ça. Elles sont par-là.
{26127}{26182}ENCYCLOPEDlE DE L'ESPACE
{26185}{26219}Les voilà.
{26222}{26333}Les dernières photos de cercles|dans les cultures du projet Argus.
{26336}{26418}- Votre avis: info ou intox?|- lntox.
{26421}{26486}Et les traces sur les plantes?
{26489}{26547}Peut-être un effet météorologique
{26550}{26619}ou une réaction de la plante|à une position donnée.
{26622}{26680}- Vous avez lu la doc'.|- Je me tiens à jour.
{26683}{26747}- Et...|- Vous vouliez nous montrer quelque chose.
{26750}{26776}Ah, oui, oui.
{26799}{26858}L'Oreille de Loup 2000. Vous connaissez?
{26861}{26950}Oui. La Société du Loup fournit|le matériel de surveillance de la ClA.
{26953}{27041}Interception et recherche de pointe.|100 canaux par seconde.
{27044}{27143}Je suis branché sur la police locale,|les pompiers, les téléphones portables,
{27146}{27253}et, si la météo le permet, sur la tour|de contrôle de la base de Whitmarsh.
{27256}{27288}Qu'avez-vous, Max?
{27317}{27397}Un message de l'unité mobile|en mode numérisé.
{27400}{27474}Service du shérif de Townsend,|il y a 2 nuits.
{27498}{27562}Incendie sur Ia départementale D7,
{27565}{27634}3 km à I'ouest|du croisement de Canyon Ridge.
{27637}{27696}Envoyez Ies pompiers. A vous.
{27699}{27750}Ici Ie shérif adjoint Wright. Reçu?
{27769}{27874}Et puis ceci, 35 minutes plus tard,|sans doute des pompiers.
{27877}{27934}La réception est brouillée.
{27937}{28031}Ici unité 53. Un homme à terre.|Envoyez des secours.
{28034}{28088}J'ai dit, envoyez des secours!
{28107}{28212}On ne vous reçoit plus... faible...|mauvais, très mauvais.
{28215}{28272}Attendez un peu. Nom de Dieu...?
{28275}{28355}Charlie! On a un problème ici!
{28410}{28454}On fait un quadrillage serré.
{28457}{28573}Oui. Chaque cm² est couvert,|creusé et passé au peigne fin.
{28576}{28632}Non, il ne nous échappera pas.
{28635}{28689}Pas cette fois.
{28722}{28805}LYCEE DE MILL ROAD|CENTRE D'EVACUATION D'URGENCE
{28808}{28873}18H27 2E JOUR
{29175}{29214}Mme Wright?
{29235}{29314}Bonjour, nous sommes Fox Mulder|et Dana Scully du FBI.
{29317}{29378}Nous avons des questions|à propos de votre mari.
{29381}{29420}Il est mort!
{29423}{29472}Que voulez-vous savoir de plus?
{29632}{29697}- Je suis désolée.|- Oh, s'il vous plaît!
{29700}{29775}- Nous voulons vous aider.|- Alors laissez-moi tranquille!
{29778}{29862}- Pourquoi ne pas nous laisser vous aider?|- Je ne sais rien!
{30050}{30106}Vous ne comprenez donc pas?
{30109}{30224}Ils ne veulent pas me rendre|le corps pour un enterrement décent?
{30227}{30293}Le gouvernement ne peut pas faire ça.
{30296}{30389}- Je suis sûre qu'en faisant appel...|- Non! Vous ne pouvez pas.
{30392}{30437}Vous avez droit à la vérité.
{30440}{30507}Je ne peux pas me le permettre.
{30561}{30662}Ils ont dit que si je parlais,|ils bloqueraient la pension de mon mari.
{30665}{30719}Et j'ai un enfant à élever.
{30923}{31012}Détectons signal à fréquence|extrêmement élevée. 200 000 mHz.
{31015}{31044}Mon colonel.
{31047}{31107}Cible du côté nord-est.
{31110}{31182}Vitesse de marche: 12 km/h, mon colonel.
{31198}{31246}- Equipe Bêta?|- Reçu.
{31249}{31305}La cible entre dans votre zone.
{31308}{31347}Trouvez et détruisez-Ia.
{31350}{31406}Je répète: trouvez et détruisez-Ia.
{31409}{31459}Reçu, mon colonel.
{32620}{32669}- Jackson?|- Rien.
{33108}{33166}Ca devait être un animal.
{33568}{33688}Désolé, mais sans autorisation,|je ne peux pas vous parler du patient.
{33691}{33742}Jason Wright était votre patient?
{33745}{33832}Je n'ai rien à vous dire.
{33835}{33931}Et à sa femme et son fils?|Avez-vous quelque chose à leur dire?
{33934}{33995}Parce qu'ils la tiennent aussi.
{33998}{34052}On a dû vous faire de sérieuses menaces.
{34055}{34149}Radiation de l'ordre des médecins?|Le fisc?
{34195}{34246}- Je hais les fascistes.|- Pardon?
{34249}{34338}Les hommes qui sont venus,|la façon dont ils nous ont bousculés.
{34429}{34531}Dr Oppenheim, parlez-nous de Wright.|Vous l'avez vu cette nuit là, non?
{34575}{34629}Oui, ainsi que trois pompiers.
{34632}{34739}Ils sont arrivés morts,|brûlés aux 5e et 6e degrés, sur 90% du corps.
{34742}{34808}Mais je n'avais jamais vu de telles brûlures.
{34811}{34888}Ils les ont emmenés|avant que nous fassions un diagnostic.
{34913}{34988}Y avait-il une rigidité cadavérique|due à la chaleur?
{34991}{35081}Oui, et de la flexion dans les membres.|Comment en savez-vous autant?
{35084}{35168}J'ai fait mon internat en médecine légale,|alors...
{35171}{35297}Docteur, ces brûlures peuvent-elles|être la conséquence de radiations ioniques?
{35326}{35365}Je n'y avais pas pensé...
{35368}{35482}Je pense que c'est possible,|si l'exposition était assez intense.
{35554}{35613}Disons qu'ils soient morts de radiations.
{35616}{35727}- Causées par une ogive nucléaire?|- J'ai lu des articles sur ces brûlures.
{35730}{35836}- Moi aussi, sur Hiroshima au niveau zéro.|- Je parle de rencontres du 3e type.
{35839}{35929}J'ai plein d'affaires N-C|indiquant les mêmes résultats cliniques.
{35932}{35985}Je n'ai pas réponse à tout,
{35988}{36060}mais si on ne se présente pas|au comité demain
{36063}{36112}Ies affaires N-C n'existeront plus.
{37186}{37260}Faites une intra-veineuse.|Saline à 150.
{37263}{37372}- Dites-nous ce qui s'est passé.|- Mulder, ça ne vous regarde pas.
{37375}{37466}Faux, mon colonel. On veut la même chose,|mais vous la voulez morte.
{37469}{37576}En la traquant comme un animal,|vous la forcez à se défendre!
{37579}{37661}Combien de morts voulez-vous|avant de repenser votre approche?
{37664}{37739}Ecoutez-moi,|parce que je ne le répéterai pas.
{37742}{37846}- Si vous êtes encore là dans 30 secondes...|- L'agent Scully reste ici!
{37849}{37913}On est en sous-effectif et elle est médecin.
{37915}{37967}- Si vous êtes d'accord.|- Bien sûr.
{37970}{38064}Docteur, occupez-vous de mes hommes|et laissez-moi faire mon boulot.
{38127}{38246}Dehors, vous faites ce que vous voulez,|mais ici c'est moi le patron.
{38268}{38367}Sauf si vous préférez|vous occuper vous-même de vos hommes.
{38437}{38481}Faites sortir cet homme.
{38484}{38533}Bien, mon colonel.
{38569}{38617}Où puis-je me nettoyer?
{38997}{39041}Max?
{39065}{39114}Hé, Max?
{39132}{39181}Max?
{40191}{40235}Hé, Max.
{40271}{40320}Qui... qui êtes vous?
{40377}{40426}Max, c'est moi. Fox Mulder.
{40461}{40510}Ca va?
{40544}{40593}Qu'est-ce que vous faites là?
{40694}{40756}Vous avez eu une crise d'épilepsie.
{40759}{40814}Une crise?
{40817}{40866}C'est impossible.
{41016}{41101}Vous étiez sur le sol,|inconscient, agité de convulsions.
{41129}{41184}C'est étrange.
{41187}{41296}Ca ne m'est pas arrivé depuis sept ans,|pas depuis mon traitement.
{41379}{41433}- Je vous conduis à l'hôpital.|- Non!
{41454}{41503}Enfin, ce n'est pas nécessaire.
{41506}{41575}- Vraiment?|- Oui, j'ai toujours été épileptique.
{41578}{41627}Je ne suis pas en danger.
{41977}{42049}Ca a commencé dans le Dakota|quand j'avais 10 ans.
{42075}{42194}Selon le médecin, j'aurais heurté ma tête,|mais je ne m'en souviens pas.
{42197}{42261}Vous souvenez-vous de la crise|une fois passée?
{42299}{42418}Enfant, je me réveillais dans des endroits|étranges sans savoir où j'étais.
{42576}{42610}Je suis désolé. Je dois...
{42613}{42675}- Je dois... Je dois dormir.|- D'accord.
{43523}{43645}..Cicatrice de 3cm sous...
{44058}{44103}Dure nuit, hein?
{44106}{44161}C'était horrible.
{44164}{44219}On les a tous perdus sauf deux.
{44222}{44339}Leur état est critique, on les envoie|au service des grands brûlés de Hopkins.
{44366}{44447}Alors qu'en penses-tu, Scully?|Que se passe-t-il ici?
{44473}{44517}Je ne sais pas.
{44520}{44603}Et, dans d'autres circonstances,|j'aimerais le savoir,
{44606}{44680}mais notre avion part|dans un peu plus d'une heure.
{44683}{44751}Jette un oeil là-dessus avant.
{44754}{44811}- Quoi?|- Max.
{44814}{44938}Il a une incision anormale derrière|l'oreille gauche. J'ai déjà vu ça deux fois.
{44975}{45032}Deux femmes, séparées par 1500 km.
{45035}{45089}Elles ne se connaissent pas, aucun lien.
{45092}{45158}Des extraterrestres les auraient enlevées.
{45198}{45262}Max Fenig aurait été enlevé?
{45303}{45337}Mulder,
{45340}{45462}ce type prend des anti-psychotiques|très forts. Je les ai vus dans sa caravane.
{45465}{45523}- C'est pour son épilepsie.|- Pas tous.
{45526}{45669}Le Mellaril est utilisé exclusivement|pour traiter la schizophrénie.
{45672}{45727}Max a sûrement des hallucinations.
{45750}{45799}Tu ne comprends pas, Scully.
{45802}{45887}Max ne croit pas avoir été enlevé,|c'est moi qui le pense.
{45937}{46034}Regarde cette cicatrice au moins|et donne-moi un avis médical?
{46125}{46174}OK.
{46177}{46254}Prépare-toi, j'examinerai Max
{46257}{46306}sur le chemin de l'aéroport.
{46376}{46441}Objet détecté dans la zoner 24.18.
{46475}{46594}Pas de réponse à nos appels|et ça n'est pas dans l'inventaire orbital.
{46597}{46672}- 24.18. C'est là...?|- Exactement au même endroit.
{46675}{46769}- Mais c'est un objet beaucoup plus gros.|- Un météore, Mlle Koretz.
{46772}{46857}Un météore beaucoup plus gros...|mon lieutenant.
{46860}{46940}- Ici base de Whitmarsh. Objet détecté.|- Attendez.
{46943}{47019}On a une confirmation.|La base de Whitmarsh l'a détecté.
{47022}{47091}- Où est-il?|- Secteur 35, 1600 km, vitesse nulle.
{47094}{47222}Mon lieutenant, le météore semble|planer au-dessus d'une ville du Wisconsin.
{47225}{47269}Objet détecté. Confirmation.
{48612}{48692}Allez, Mulder. Qu'on en finisse.
{48729}{48778}Hé, Max?
{48792}{48821}Max!
{48870}{48914}Max?
{48933}{48982}Hé, Max?
{49139}{49188}Max?
{49200}{49249}Mulder, regarde ça.
{49273}{49327}Qu'est-ce que c'est? Du sang?
{49486}{49566}Patrouille Faucon. Intrus non-identifié.
{49569}{49693}Je répète: patrouille Faucon.|Intrus non-identifié au port, quai 7.
{49804}{49843}- Mulder!|- Allons-y!
{49846}{49895}Où crois-tu aller comme ça?
{49898}{49971}Si on part maintenant,|on peut encore avoir l'avion,
{49974}{50045}ce qui te donnerait une chance|de te défendre.
{50048}{50126}Réfléchis, Scully.|Max est un gitan, un nomade, non?
{50129}{50168}Oui. Et alors?
{50171}{50235}Il a intercepté le dernier appel de Wright,
{50237}{50320}donc il était à Townsend la nuit de l'accident.
{50323}{50388}Il aurait pu être partout, mais il était là.
{50391}{50450}C'est plus qu'une coïncidence, non?
{50453}{50530}Si Max a été enlevé,|ça expliquerait ses obsessions.
{50533}{50603}Et si nous avons deviné ça, Henderson aussi.
{50606}{50655}Tu as les clés?
{50842}{50926}RlVE DU LAC MlCHlGAN|QUAl 7
{51336}{51421}- Ne faites pas ça!|- Mon colonel, on a la cible. C'est un civil.
{51424}{51500}Négatif, patrouille Faucon.|Prenez-le avec prudence.
{52034}{52088}Ils sont morts.
{52418}{52462}J'ai mal. Arrêtez.
{52465}{52502}Pourquoi, pourquoi?
{52505}{52565}Ca fait mal. Ca fait mal. Ca fait mal...
{52568}{52619}- Max?|- Ca fait mal. Ca fait mal.
{52622}{52694}Arrêtez, ça fait mal.|Arrêtez, ça fait mal...
{52697}{52769}- Ca ira.|- Arrêtez, ça fait mal...
{52772}{52847}Non. Non, c'est moi.|Ils viennent me chercher.
{52886}{52960}Maintenant je sais...|Ils viennent me chercher....
{53008}{53062}- Ca fait mal...|- Retiens-les.
{53387}{53433}Equipe Alpha, bloquez le toit.
{53508}{53591}Ne bougez plus!|Les mains en l'air et suivez-nous!
{53641}{53690}Aidez-moi!
{53693}{53742}Allez! Allez! Allez!
{53792}{53841}Quadrant 4, allez-y!
{53960}{54009}Equipe Alpha en position sur le toit.
{54049}{54105}Reçu, Alpha. Equipe Delta, à vous.
{54108}{54157}Equipe Delta en position.
{54229}{54301}Que faites-vous?|Un homme malade est à l'intérieur.
{54304}{54396}On n'est plus à l'hôpital, Dr Scully.|Equipe Oméga, à vous.
{54399}{54481}- Equipe Oméga en position.|- Un schizophrène.
{54484}{54533}Ecartez-la.
{54550}{54672}Ici leader équipe Alpha.|Je visualise trois formes dans le bâtiment.
{54675}{54725}Vous avez dit trois?
{54728}{54779}Affirmatif.
{54782}{54829}Deux sont proches l'une de l'autre.
{54864}{54908}La troisième,
{54911}{54960}approche à 40 mètres.
{55022}{55084}A toutes les équipes,|on y va dans 30 secondes.
{55087}{55141}Allez! Allez, Max.
{55144}{55193}Arrêtez. Pourquoi...
{55196}{55245}Je suis là pour vous aider.
{55292}{55344}- J'ai peur.|- Je sais.
{55347}{55440}- Ne les laissez pas me prendre.|- Je ne les laisserai pas faire.
{55443}{55502}Allez, Max. Suivez-moi.
{55531}{55576}Non!
{55760}{55804}Max!
{55961}{56005}Max!
{56194}{56238}Max!
{56429}{56458}Max!
{57030}{57164}Ici Ieader AIpha. A part nos hommes,|je ne vois qu'une forme à I'intérieur.
{57167}{57201}Répétez.
{57204}{57290}On ne visualise|qu'une seule forme à l'intérieur.
{57293}{57362}- Quoi?|- Faites sauter Ia porte!
{57439}{57488}Prenez-le!
{57780}{57824}Où est-il?
{57859}{57903}Il a disparu.
{57906}{57991}Ils nous ont devancés.|Ils nous ont battus, colonel.
{58017}{58066}Arrêtez-le.
{58108}{58157}Et continuez à chercher!
{58221}{58278}SlEGE DU FBl|WASHlNGTON, DC
{58290}{58391}Agent Scully,|l'agent Mulder avait-il pour mission
{58394}{58506}d'enquêter sur des affaires relatives|à l'évacuation de Townsend, Wisconsin?
{58509}{58553}Non, monsieur.
{58556}{58640}Savez-vous si l'agent Mulder|avait présenté un formulaire 302,
{58643}{58724}demandant la dite mission|ou des frais de transport?
{58727}{58770}Non, monsieur.
{58773}{58884}Dans le Wisconsin, l'agent Mulder|conduisait-il une Ford Taurus bleue,
{58888}{58949}portant une immatriculation fédérale?
{58952}{58996}Oui, monsieur.
{58999}{59048}Merci, agent Scully.
{59051}{59143}- J'aimerais faire une déclaration.|- Demande refusée.
{59146}{59220}Il est injuste de juger Mulder|selon les critères que...
{59223}{59287}Vous pouvez disposer, agent Scully.
{59289}{59355}- Mais, Monsieur...|- Ce sera tout!
{59656}{59746}Tu entends ces bruits, Scully?|Un marteau et des clous.
{59749}{59821}Ils élèvent la potence|sur la place du village.
{59852}{59896}Ne t'en fais pas.
{59899}{59943}Ca devait arriver.
{59946}{59997}Avoir tenu si longtemps est étonnant.
{60025}{60074}Bonne chance.
{60077}{60126}Merci, je ferai attention.
{60483}{60545}DECHETS TOXlQUES ELlMlNES
{60602}{60675}..insubordination et faute professionnelle.
{60678}{60784}Que répondez-vous à ces accusations,|agent Mulder?
{60787}{60901}Douze hommes sont morts et je dois|me justifier sur des questions de protocole?
{60904}{61026}- Vous n'avez pas demandé d'autorisation.|- Je savais qu'on me la refuserait.
{61029}{61126}- et violé une quarantaine fédérale...|- Une opération de camouflage!
{61129}{61214}vous exposant,|ainsi qu'autrui, à une pollution toxique.
{61217}{61268}Pollution toxique! On en reparle?
{61271}{61337}Vous avez lu mon rapport.|Et la disparition de Fenig?
{61340}{61449}- L'enquête ne concerne pas votre rapport.|- J'ai d'autres preuves!
{61452}{61566}Des radios de M. Fenig montrent|la présence d'un objet dans son cervelet.
{61569}{61618}C'est hors de propos, agent Mulder.
{61621}{61703}Il a été enlevé par des extraterrestres.|Nous le savons tous!
{61706}{61798}Le témoignage du colonel Henderson révèle
{61801}{61895}qu'on a retrouvé le corps de Fenig|2 heures plus tard, dans un container.
{62016}{62065}Que puis-je dire alors?
{62104}{62195}Comment réfuter des mensonges|marqués du sceau officiel?
{62198}{62257}Ce sera tout, M. Mulder.
{62260}{62383}Vous pouvez nier tout ce que j'ai vu,|tout ce que j'ai découvert,
{62386}{62430}mais plus pour longtemps.
{62433}{62505}Parce que trop de gens savent|ce qui se passe.
{62508}{62565}Et personne,
{62568}{62659}aucune agence gouvernementale,|ne peut cacher la vérité.
{63422}{63480}Pourquoi avoir annulé notre décision?
{63483}{63605}Mulder avait clairement violé|la loi fédérale et notre propre procédure.
{63608}{63642}Oui.
{63645}{63735}Je ne comprends pas.|Le dossier du comité était très complet.
{63738}{63808}Vous avez ruiné notre chance|de nous en débarrasser.
{63811}{63865}Je comprends votre frustration,
{63868}{63964}mais vous et moi savons|que le travail de Mulder est...
{63967}{64027}sa seule passion.
{64030}{64089}Ce qui pose un dilemme unique.
{64121}{64246}Mais son insubordination occasionnelle,|est en somme, bien moins dangereuse.
{64249}{64320}Sauf votre respect,|moins dangereuse que quoi?
{64323}{64415}Que de le voir dévoiler à mauvais escient
{64418}{64470}ce qu'il sait.
{64488}{64537}Ce qu'il croit savoir.
{64588}{64694}Soyez toujours proche de vos amis,|M. McGrath.
{64738}{64797}Mais soyez encore plus proche|de vos ennemis.
{65510}{65583}Sous-titrage Visiontext: Mathieu Playoult
{65884}{65923}C'est moi qui I'ai fait!
{65935}{65984}FRENCH
